// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.20.3
// source: ultipa.proto

package ultipa

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	UltipaRpcs_SayHello_FullMethodName    = "/ultipa.UltipaRpcs/SayHello"
	UltipaRpcs_Query_FullMethodName       = "/ultipa.UltipaRpcs/Query"
	UltipaRpcs_InsertNodes_FullMethodName = "/ultipa.UltipaRpcs/InsertNodes"
	UltipaRpcs_InsertEdges_FullMethodName = "/ultipa.UltipaRpcs/InsertEdges"
)

// UltipaRpcsClient is the client API for UltipaRpcs service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UltipaRpcsClient interface {
	// Sends a greeting
	SayHello(ctx context.Context, in *HelloUltipaRequest, opts ...grpc.CallOption) (*HelloUltipaReply, error)
	// Query
	Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (UltipaRpcs_QueryClient, error)
	// 插入点
	InsertNodes(ctx context.Context, in *InsertNodesRequest, opts ...grpc.CallOption) (*InsertNodesReply, error)
	// 插入边
	InsertEdges(ctx context.Context, in *InsertEdgesRequest, opts ...grpc.CallOption) (*InsertEdgesReply, error)
}

type ultipaRpcsClient struct {
	cc grpc.ClientConnInterface
}

func NewUltipaRpcsClient(cc grpc.ClientConnInterface) UltipaRpcsClient {
	return &ultipaRpcsClient{cc}
}

func (c *ultipaRpcsClient) SayHello(ctx context.Context, in *HelloUltipaRequest, opts ...grpc.CallOption) (*HelloUltipaReply, error) {
	out := new(HelloUltipaReply)
	err := c.cc.Invoke(ctx, UltipaRpcs_SayHello_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ultipaRpcsClient) Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (UltipaRpcs_QueryClient, error) {
	stream, err := c.cc.NewStream(ctx, &UltipaRpcs_ServiceDesc.Streams[0], UltipaRpcs_Query_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &ultipaRpcsQueryClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type UltipaRpcs_QueryClient interface {
	Recv() (*QueryReply, error)
	grpc.ClientStream
}

type ultipaRpcsQueryClient struct {
	grpc.ClientStream
}

func (x *ultipaRpcsQueryClient) Recv() (*QueryReply, error) {
	m := new(QueryReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *ultipaRpcsClient) InsertNodes(ctx context.Context, in *InsertNodesRequest, opts ...grpc.CallOption) (*InsertNodesReply, error) {
	out := new(InsertNodesReply)
	err := c.cc.Invoke(ctx, UltipaRpcs_InsertNodes_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ultipaRpcsClient) InsertEdges(ctx context.Context, in *InsertEdgesRequest, opts ...grpc.CallOption) (*InsertEdgesReply, error) {
	out := new(InsertEdgesReply)
	err := c.cc.Invoke(ctx, UltipaRpcs_InsertEdges_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UltipaRpcsServer is the server API for UltipaRpcs service.
// All implementations must embed UnimplementedUltipaRpcsServer
// for forward compatibility
type UltipaRpcsServer interface {
	// Sends a greeting
	SayHello(context.Context, *HelloUltipaRequest) (*HelloUltipaReply, error)
	// Query
	Query(*QueryRequest, UltipaRpcs_QueryServer) error
	// 插入点
	InsertNodes(context.Context, *InsertNodesRequest) (*InsertNodesReply, error)
	// 插入边
	InsertEdges(context.Context, *InsertEdgesRequest) (*InsertEdgesReply, error)
	mustEmbedUnimplementedUltipaRpcsServer()
}

// UnimplementedUltipaRpcsServer must be embedded to have forward compatible implementations.
type UnimplementedUltipaRpcsServer struct {
}

func (UnimplementedUltipaRpcsServer) SayHello(context.Context, *HelloUltipaRequest) (*HelloUltipaReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedUltipaRpcsServer) Query(*QueryRequest, UltipaRpcs_QueryServer) error {
	return status.Errorf(codes.Unimplemented, "method Query not implemented")
}
func (UnimplementedUltipaRpcsServer) InsertNodes(context.Context, *InsertNodesRequest) (*InsertNodesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InsertNodes not implemented")
}
func (UnimplementedUltipaRpcsServer) InsertEdges(context.Context, *InsertEdgesRequest) (*InsertEdgesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InsertEdges not implemented")
}
func (UnimplementedUltipaRpcsServer) mustEmbedUnimplementedUltipaRpcsServer() {}

// UnsafeUltipaRpcsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UltipaRpcsServer will
// result in compilation errors.
type UnsafeUltipaRpcsServer interface {
	mustEmbedUnimplementedUltipaRpcsServer()
}

func RegisterUltipaRpcsServer(s grpc.ServiceRegistrar, srv UltipaRpcsServer) {
	s.RegisterService(&UltipaRpcs_ServiceDesc, srv)
}

func _UltipaRpcs_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloUltipaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UltipaRpcsServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UltipaRpcs_SayHello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UltipaRpcsServer).SayHello(ctx, req.(*HelloUltipaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UltipaRpcs_Query_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(QueryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UltipaRpcsServer).Query(m, &ultipaRpcsQueryServer{stream})
}

type UltipaRpcs_QueryServer interface {
	Send(*QueryReply) error
	grpc.ServerStream
}

type ultipaRpcsQueryServer struct {
	grpc.ServerStream
}

func (x *ultipaRpcsQueryServer) Send(m *QueryReply) error {
	return x.ServerStream.SendMsg(m)
}

func _UltipaRpcs_InsertNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UltipaRpcsServer).InsertNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UltipaRpcs_InsertNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UltipaRpcsServer).InsertNodes(ctx, req.(*InsertNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UltipaRpcs_InsertEdges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertEdgesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UltipaRpcsServer).InsertEdges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UltipaRpcs_InsertEdges_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UltipaRpcsServer).InsertEdges(ctx, req.(*InsertEdgesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UltipaRpcs_ServiceDesc is the grpc.ServiceDesc for UltipaRpcs service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UltipaRpcs_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ultipa.UltipaRpcs",
	HandlerType: (*UltipaRpcsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _UltipaRpcs_SayHello_Handler,
		},
		{
			MethodName: "InsertNodes",
			Handler:    _UltipaRpcs_InsertNodes_Handler,
		},
		{
			MethodName: "InsertEdges",
			Handler:    _UltipaRpcs_InsertEdges_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Query",
			Handler:       _UltipaRpcs_Query_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "ultipa.proto",
}

const (
	UltipaControls_SayHello_FullMethodName      = "/ultipa.UltipaControls/SayHello"
	UltipaControls_UserSetting_FullMethodName   = "/ultipa.UltipaControls/UserSetting"
	UltipaControls_QueryEx_FullMethodName       = "/ultipa.UltipaControls/QueryEx"
	UltipaControls_Export_FullMethodName        = "/ultipa.UltipaControls/Export"
	UltipaControls_DownloadFile_FullMethodName  = "/ultipa.UltipaControls/DownloadFile"
	UltipaControls_InstallAlgo_FullMethodName   = "/ultipa.UltipaControls/InstallAlgo"
	UltipaControls_UninstallAlgo_FullMethodName = "/ultipa.UltipaControls/UninstallAlgo"
	UltipaControls_RollbackAlgo_FullMethodName  = "/ultipa.UltipaControls/RollbackAlgo"
	UltipaControls_Authenticate_FullMethodName  = "/ultipa.UltipaControls/Authenticate"
)

// UltipaControlsClient is the client API for UltipaControls service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UltipaControlsClient interface {
	// Sends a greeting
	SayHello(ctx context.Context, in *HelloUltipaRequest, opts ...grpc.CallOption) (*HelloUltipaReply, error)
	// 用户设置(用于存储用户配置信息,用户自主控制)
	UserSetting(ctx context.Context, in *UserSettingRequest, opts ...grpc.CallOption) (*UserSettingReply, error)
	// query扩展，以下命令在此接口执行执行 top, kill show().* stats
	QueryEx(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (UltipaControls_QueryExClient, error)
	// 导出点,边数据
	Export(ctx context.Context, in *ExportRequest, opts ...grpc.CallOption) (UltipaControls_ExportClient, error)
	// 下载算法生成文件
	DownloadFile(ctx context.Context, in *DownloadFileRequest, opts ...grpc.CallOption) (UltipaControls_DownloadFileClient, error)
	// 算法安装
	InstallAlgo(ctx context.Context, opts ...grpc.CallOption) (UltipaControls_InstallAlgoClient, error)
	// 算法卸载
	UninstallAlgo(ctx context.Context, in *UninstallAlgoRequest, opts ...grpc.CallOption) (*UninstallAlgoReply, error)
	// 算法回退
	RollbackAlgo(ctx context.Context, in *RollbackAlgoRequest, opts ...grpc.CallOption) (*RollbackAlgoReply, error)
	// 仅鉴权
	Authenticate(ctx context.Context, in *AuthenticateRequest, opts ...grpc.CallOption) (*AuthenticateReply, error)
}

type ultipaControlsClient struct {
	cc grpc.ClientConnInterface
}

func NewUltipaControlsClient(cc grpc.ClientConnInterface) UltipaControlsClient {
	return &ultipaControlsClient{cc}
}

func (c *ultipaControlsClient) SayHello(ctx context.Context, in *HelloUltipaRequest, opts ...grpc.CallOption) (*HelloUltipaReply, error) {
	out := new(HelloUltipaReply)
	err := c.cc.Invoke(ctx, UltipaControls_SayHello_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ultipaControlsClient) UserSetting(ctx context.Context, in *UserSettingRequest, opts ...grpc.CallOption) (*UserSettingReply, error) {
	out := new(UserSettingReply)
	err := c.cc.Invoke(ctx, UltipaControls_UserSetting_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ultipaControlsClient) QueryEx(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (UltipaControls_QueryExClient, error) {
	stream, err := c.cc.NewStream(ctx, &UltipaControls_ServiceDesc.Streams[0], UltipaControls_QueryEx_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &ultipaControlsQueryExClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type UltipaControls_QueryExClient interface {
	Recv() (*QueryReply, error)
	grpc.ClientStream
}

type ultipaControlsQueryExClient struct {
	grpc.ClientStream
}

func (x *ultipaControlsQueryExClient) Recv() (*QueryReply, error) {
	m := new(QueryReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *ultipaControlsClient) Export(ctx context.Context, in *ExportRequest, opts ...grpc.CallOption) (UltipaControls_ExportClient, error) {
	stream, err := c.cc.NewStream(ctx, &UltipaControls_ServiceDesc.Streams[1], UltipaControls_Export_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &ultipaControlsExportClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type UltipaControls_ExportClient interface {
	Recv() (*ExportReply, error)
	grpc.ClientStream
}

type ultipaControlsExportClient struct {
	grpc.ClientStream
}

func (x *ultipaControlsExportClient) Recv() (*ExportReply, error) {
	m := new(ExportReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *ultipaControlsClient) DownloadFile(ctx context.Context, in *DownloadFileRequest, opts ...grpc.CallOption) (UltipaControls_DownloadFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &UltipaControls_ServiceDesc.Streams[2], UltipaControls_DownloadFile_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &ultipaControlsDownloadFileClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type UltipaControls_DownloadFileClient interface {
	Recv() (*DownloadFileReply, error)
	grpc.ClientStream
}

type ultipaControlsDownloadFileClient struct {
	grpc.ClientStream
}

func (x *ultipaControlsDownloadFileClient) Recv() (*DownloadFileReply, error) {
	m := new(DownloadFileReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *ultipaControlsClient) InstallAlgo(ctx context.Context, opts ...grpc.CallOption) (UltipaControls_InstallAlgoClient, error) {
	stream, err := c.cc.NewStream(ctx, &UltipaControls_ServiceDesc.Streams[3], UltipaControls_InstallAlgo_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &ultipaControlsInstallAlgoClient{stream}
	return x, nil
}

type UltipaControls_InstallAlgoClient interface {
	Send(*InstallAlgoRequest) error
	CloseAndRecv() (*InstallAlgoReply, error)
	grpc.ClientStream
}

type ultipaControlsInstallAlgoClient struct {
	grpc.ClientStream
}

func (x *ultipaControlsInstallAlgoClient) Send(m *InstallAlgoRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *ultipaControlsInstallAlgoClient) CloseAndRecv() (*InstallAlgoReply, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(InstallAlgoReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *ultipaControlsClient) UninstallAlgo(ctx context.Context, in *UninstallAlgoRequest, opts ...grpc.CallOption) (*UninstallAlgoReply, error) {
	out := new(UninstallAlgoReply)
	err := c.cc.Invoke(ctx, UltipaControls_UninstallAlgo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ultipaControlsClient) RollbackAlgo(ctx context.Context, in *RollbackAlgoRequest, opts ...grpc.CallOption) (*RollbackAlgoReply, error) {
	out := new(RollbackAlgoReply)
	err := c.cc.Invoke(ctx, UltipaControls_RollbackAlgo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ultipaControlsClient) Authenticate(ctx context.Context, in *AuthenticateRequest, opts ...grpc.CallOption) (*AuthenticateReply, error) {
	out := new(AuthenticateReply)
	err := c.cc.Invoke(ctx, UltipaControls_Authenticate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UltipaControlsServer is the server API for UltipaControls service.
// All implementations must embed UnimplementedUltipaControlsServer
// for forward compatibility
type UltipaControlsServer interface {
	// Sends a greeting
	SayHello(context.Context, *HelloUltipaRequest) (*HelloUltipaReply, error)
	// 用户设置(用于存储用户配置信息,用户自主控制)
	UserSetting(context.Context, *UserSettingRequest) (*UserSettingReply, error)
	// query扩展，以下命令在此接口执行执行 top, kill show().* stats
	QueryEx(*QueryRequest, UltipaControls_QueryExServer) error
	// 导出点,边数据
	Export(*ExportRequest, UltipaControls_ExportServer) error
	// 下载算法生成文件
	DownloadFile(*DownloadFileRequest, UltipaControls_DownloadFileServer) error
	// 算法安装
	InstallAlgo(UltipaControls_InstallAlgoServer) error
	// 算法卸载
	UninstallAlgo(context.Context, *UninstallAlgoRequest) (*UninstallAlgoReply, error)
	// 算法回退
	RollbackAlgo(context.Context, *RollbackAlgoRequest) (*RollbackAlgoReply, error)
	// 仅鉴权
	Authenticate(context.Context, *AuthenticateRequest) (*AuthenticateReply, error)
	mustEmbedUnimplementedUltipaControlsServer()
}

// UnimplementedUltipaControlsServer must be embedded to have forward compatible implementations.
type UnimplementedUltipaControlsServer struct {
}

func (UnimplementedUltipaControlsServer) SayHello(context.Context, *HelloUltipaRequest) (*HelloUltipaReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedUltipaControlsServer) UserSetting(context.Context, *UserSettingRequest) (*UserSettingReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserSetting not implemented")
}
func (UnimplementedUltipaControlsServer) QueryEx(*QueryRequest, UltipaControls_QueryExServer) error {
	return status.Errorf(codes.Unimplemented, "method QueryEx not implemented")
}
func (UnimplementedUltipaControlsServer) Export(*ExportRequest, UltipaControls_ExportServer) error {
	return status.Errorf(codes.Unimplemented, "method Export not implemented")
}
func (UnimplementedUltipaControlsServer) DownloadFile(*DownloadFileRequest, UltipaControls_DownloadFileServer) error {
	return status.Errorf(codes.Unimplemented, "method DownloadFile not implemented")
}
func (UnimplementedUltipaControlsServer) InstallAlgo(UltipaControls_InstallAlgoServer) error {
	return status.Errorf(codes.Unimplemented, "method InstallAlgo not implemented")
}
func (UnimplementedUltipaControlsServer) UninstallAlgo(context.Context, *UninstallAlgoRequest) (*UninstallAlgoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UninstallAlgo not implemented")
}
func (UnimplementedUltipaControlsServer) RollbackAlgo(context.Context, *RollbackAlgoRequest) (*RollbackAlgoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RollbackAlgo not implemented")
}
func (UnimplementedUltipaControlsServer) Authenticate(context.Context, *AuthenticateRequest) (*AuthenticateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Authenticate not implemented")
}
func (UnimplementedUltipaControlsServer) mustEmbedUnimplementedUltipaControlsServer() {}

// UnsafeUltipaControlsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UltipaControlsServer will
// result in compilation errors.
type UnsafeUltipaControlsServer interface {
	mustEmbedUnimplementedUltipaControlsServer()
}

func RegisterUltipaControlsServer(s grpc.ServiceRegistrar, srv UltipaControlsServer) {
	s.RegisterService(&UltipaControls_ServiceDesc, srv)
}

func _UltipaControls_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloUltipaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UltipaControlsServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UltipaControls_SayHello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UltipaControlsServer).SayHello(ctx, req.(*HelloUltipaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UltipaControls_UserSetting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserSettingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UltipaControlsServer).UserSetting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UltipaControls_UserSetting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UltipaControlsServer).UserSetting(ctx, req.(*UserSettingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UltipaControls_QueryEx_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(QueryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UltipaControlsServer).QueryEx(m, &ultipaControlsQueryExServer{stream})
}

type UltipaControls_QueryExServer interface {
	Send(*QueryReply) error
	grpc.ServerStream
}

type ultipaControlsQueryExServer struct {
	grpc.ServerStream
}

func (x *ultipaControlsQueryExServer) Send(m *QueryReply) error {
	return x.ServerStream.SendMsg(m)
}

func _UltipaControls_Export_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExportRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UltipaControlsServer).Export(m, &ultipaControlsExportServer{stream})
}

type UltipaControls_ExportServer interface {
	Send(*ExportReply) error
	grpc.ServerStream
}

type ultipaControlsExportServer struct {
	grpc.ServerStream
}

func (x *ultipaControlsExportServer) Send(m *ExportReply) error {
	return x.ServerStream.SendMsg(m)
}

func _UltipaControls_DownloadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownloadFileRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UltipaControlsServer).DownloadFile(m, &ultipaControlsDownloadFileServer{stream})
}

type UltipaControls_DownloadFileServer interface {
	Send(*DownloadFileReply) error
	grpc.ServerStream
}

type ultipaControlsDownloadFileServer struct {
	grpc.ServerStream
}

func (x *ultipaControlsDownloadFileServer) Send(m *DownloadFileReply) error {
	return x.ServerStream.SendMsg(m)
}

func _UltipaControls_InstallAlgo_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(UltipaControlsServer).InstallAlgo(&ultipaControlsInstallAlgoServer{stream})
}

type UltipaControls_InstallAlgoServer interface {
	SendAndClose(*InstallAlgoReply) error
	Recv() (*InstallAlgoRequest, error)
	grpc.ServerStream
}

type ultipaControlsInstallAlgoServer struct {
	grpc.ServerStream
}

func (x *ultipaControlsInstallAlgoServer) SendAndClose(m *InstallAlgoReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *ultipaControlsInstallAlgoServer) Recv() (*InstallAlgoRequest, error) {
	m := new(InstallAlgoRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _UltipaControls_UninstallAlgo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UninstallAlgoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UltipaControlsServer).UninstallAlgo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UltipaControls_UninstallAlgo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UltipaControlsServer).UninstallAlgo(ctx, req.(*UninstallAlgoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UltipaControls_RollbackAlgo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollbackAlgoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UltipaControlsServer).RollbackAlgo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UltipaControls_RollbackAlgo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UltipaControlsServer).RollbackAlgo(ctx, req.(*RollbackAlgoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UltipaControls_Authenticate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthenticateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UltipaControlsServer).Authenticate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UltipaControls_Authenticate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UltipaControlsServer).Authenticate(ctx, req.(*AuthenticateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UltipaControls_ServiceDesc is the grpc.ServiceDesc for UltipaControls service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UltipaControls_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ultipa.UltipaControls",
	HandlerType: (*UltipaControlsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _UltipaControls_SayHello_Handler,
		},
		{
			MethodName: "UserSetting",
			Handler:    _UltipaControls_UserSetting_Handler,
		},
		{
			MethodName: "UninstallAlgo",
			Handler:    _UltipaControls_UninstallAlgo_Handler,
		},
		{
			MethodName: "RollbackAlgo",
			Handler:    _UltipaControls_RollbackAlgo_Handler,
		},
		{
			MethodName: "Authenticate",
			Handler:    _UltipaControls_Authenticate_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "QueryEx",
			Handler:       _UltipaControls_QueryEx_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Export",
			Handler:       _UltipaControls_Export_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "DownloadFile",
			Handler:       _UltipaControls_DownloadFile_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "InstallAlgo",
			Handler:       _UltipaControls_InstallAlgo_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "ultipa.proto",
}
