// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ultipa.proto

package ultipa

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UltipaPropertyType int32

const (
	UltipaPropertyType_PROPERTY_INT32  UltipaPropertyType = 0
	UltipaPropertyType_PROPERTY_STRING UltipaPropertyType = 1
	UltipaPropertyType_PROPERTY_FLOAT  UltipaPropertyType = 2
	UltipaPropertyType_PROPERTY_DOUBLE UltipaPropertyType = 3
	UltipaPropertyType_PROPERTY_UINT32 UltipaPropertyType = 4
	UltipaPropertyType_PROPERTY_INT64  UltipaPropertyType = 5
	UltipaPropertyType_PROPERTY_UINT64 UltipaPropertyType = 6
	UltipaPropertyType_PROPERTY_BLOB   UltipaPropertyType = 7
)

var UltipaPropertyType_name = map[int32]string{
	0: "PROPERTY_INT32",
	1: "PROPERTY_STRING",
	2: "PROPERTY_FLOAT",
	3: "PROPERTY_DOUBLE",
	4: "PROPERTY_UINT32",
	5: "PROPERTY_INT64",
	6: "PROPERTY_UINT64",
	7: "PROPERTY_BLOB",
}

var UltipaPropertyType_value = map[string]int32{
	"PROPERTY_INT32":  0,
	"PROPERTY_STRING": 1,
	"PROPERTY_FLOAT":  2,
	"PROPERTY_DOUBLE": 3,
	"PROPERTY_UINT32": 4,
	"PROPERTY_INT64":  5,
	"PROPERTY_UINT64": 6,
	"PROPERTY_BLOB":   7,
}

func (x UltipaPropertyType) String() string {
	return proto.EnumName(UltipaPropertyType_name, int32(x))
}

func (UltipaPropertyType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6cb30324c7364683, []int{0}
}

type ErrorCode int32

const (
	ErrorCode_SUCCESS                        ErrorCode = 0
	ErrorCode_FAILED                         ErrorCode = 1
	ErrorCode_PARAM_ERROR                    ErrorCode = 2
	ErrorCode_BASE_DB_ERROR                  ErrorCode = 3
	ErrorCode_ENGINE_ERROR                   ErrorCode = 4
	ErrorCode_SYSTEM_ERROR                   ErrorCode = 5
	ErrorCode_RAFT_REDIRECT                  ErrorCode = 6
	ErrorCode_RAFT_LEADER_NOT_YET_ELECTED    ErrorCode = 7
	ErrorCode_RAFT_LOG_ERROR                 ErrorCode = 8
	ErrorCode_UQL_ERROR                      ErrorCode = 9
	ErrorCode_NOT_RAFT_MODE                  ErrorCode = 10
	ErrorCode_RAFT_NO_AVAILABLE_FOLLOWERS    ErrorCode = 11
	ErrorCode_RAFT_NO_AVAILABLE_ALGO_SERVERS ErrorCode = 12
	//鉴权失败
	ErrorCode_PERMISSION_DENIED ErrorCode = 13
)

var ErrorCode_name = map[int32]string{
	0:  "SUCCESS",
	1:  "FAILED",
	2:  "PARAM_ERROR",
	3:  "BASE_DB_ERROR",
	4:  "ENGINE_ERROR",
	5:  "SYSTEM_ERROR",
	6:  "RAFT_REDIRECT",
	7:  "RAFT_LEADER_NOT_YET_ELECTED",
	8:  "RAFT_LOG_ERROR",
	9:  "UQL_ERROR",
	10: "NOT_RAFT_MODE",
	11: "RAFT_NO_AVAILABLE_FOLLOWERS",
	12: "RAFT_NO_AVAILABLE_ALGO_SERVERS",
	13: "PERMISSION_DENIED",
}

var ErrorCode_value = map[string]int32{
	"SUCCESS":                        0,
	"FAILED":                         1,
	"PARAM_ERROR":                    2,
	"BASE_DB_ERROR":                  3,
	"ENGINE_ERROR":                   4,
	"SYSTEM_ERROR":                   5,
	"RAFT_REDIRECT":                  6,
	"RAFT_LEADER_NOT_YET_ELECTED":    7,
	"RAFT_LOG_ERROR":                 8,
	"UQL_ERROR":                      9,
	"NOT_RAFT_MODE":                  10,
	"RAFT_NO_AVAILABLE_FOLLOWERS":    11,
	"RAFT_NO_AVAILABLE_ALGO_SERVERS": 12,
	"PERMISSION_DENIED":              13,
}

func (x ErrorCode) String() string {
	return proto.EnumName(ErrorCode_name, int32(x))
}

func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6cb30324c7364683, []int{1}
}

type FollowerRole int32

const (
	FollowerRole_ROLE_UNSET           FollowerRole = 0
	FollowerRole_ROLE_READABLE        FollowerRole = 1
	FollowerRole_ROLE_ALGO_EXECUTABLE FollowerRole = 2
	FollowerRole_ROLE_LEARNER         FollowerRole = 4
)

var FollowerRole_name = map[int32]string{
	0: "ROLE_UNSET",
	1: "ROLE_READABLE",
	2: "ROLE_ALGO_EXECUTABLE",
	4: "ROLE_LEARNER",
}

var FollowerRole_value = map[string]int32{
	"ROLE_UNSET":           0,
	"ROLE_READABLE":        1,
	"ROLE_ALGO_EXECUTABLE": 2,
	"ROLE_LEARNER":         4,
}

func (x FollowerRole) String() string {
	return proto.EnumName(FollowerRole_name, int32(x))
}

func (FollowerRole) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6cb30324c7364683, []int{2}
}

type ServerStatus int32

const (
	ServerStatus_DEAD  ServerStatus = 0
	ServerStatus_ALIVE ServerStatus = 1
)

var ServerStatus_name = map[int32]string{
	0: "DEAD",
	1: "ALIVE",
}

var ServerStatus_value = map[string]int32{
	"DEAD":  0,
	"ALIVE": 1,
}

func (x ServerStatus) String() string {
	return proto.EnumName(ServerStatus_name, int32(x))
}

func (ServerStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6cb30324c7364683, []int{3}
}

type DBType int32

const (
	DBType_DBNODE DBType = 0
	DBType_DBEDGE DBType = 1
)

var DBType_name = map[int32]string{
	0: "DBNODE",
	1: "DBEDGE",
}

var DBType_value = map[string]int32{
	"DBNODE": 0,
	"DBEDGE": 1,
}

func (x DBType) String() string {
	return proto.EnumName(DBType_name, int32(x))
}

func (DBType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6cb30324c7364683, []int{4}
}

type TASK_STATUS int32

const (
	TASK_STATUS_TASK_PENDING   TASK_STATUS = 0
	TASK_STATUS_TASK_COMPUTING TASK_STATUS = 1
	TASK_STATUS_TASK_WRITING   TASK_STATUS = 2
	TASK_STATUS_TASK_DONE      TASK_STATUS = 3
	TASK_STATUS_TASK_FAILED    TASK_STATUS = 4
	TASK_STATUS_TASK_STOPPED   TASK_STATUS = 5
)

var TASK_STATUS_name = map[int32]string{
	0: "TASK_PENDING",
	1: "TASK_COMPUTING",
	2: "TASK_WRITING",
	3: "TASK_DONE",
	4: "TASK_FAILED",
	5: "TASK_STOPPED",
}

var TASK_STATUS_value = map[string]int32{
	"TASK_PENDING":   0,
	"TASK_COMPUTING": 1,
	"TASK_WRITING":   2,
	"TASK_DONE":      3,
	"TASK_FAILED":    4,
	"TASK_STOPPED":   5,
}

func (x TASK_STATUS) String() string {
	return proto.EnumName(TASK_STATUS_name, int32(x))
}

func (TASK_STATUS) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6cb30324c7364683, []int{5}
}

type UserSettingRequest_OPTION int32

const (
	UserSettingRequest_OPT_GET UserSettingRequest_OPTION = 0
	UserSettingRequest_OPT_SET UserSettingRequest_OPTION = 1
)

var UserSettingRequest_OPTION_name = map[int32]string{
	0: "OPT_GET",
	1: "OPT_SET",
}

var UserSettingRequest_OPTION_value = map[string]int32{
	"OPT_GET": 0,
	"OPT_SET": 1,
}

func (x UserSettingRequest_OPTION) String() string {
	return proto.EnumName(UserSettingRequest_OPTION_name, int32(x))
}

func (UserSettingRequest_OPTION) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6cb30324c7364683, []int{7, 0}
}

//------------------------1.SayHello------------------------------
type HelloUltipaRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloUltipaRequest) Reset()         { *m = HelloUltipaRequest{} }
func (m *HelloUltipaRequest) String() string { return proto.CompactTextString(m) }
func (*HelloUltipaRequest) ProtoMessage()    {}
func (*HelloUltipaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cb30324c7364683, []int{0}
}

func (m *HelloUltipaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloUltipaRequest.Unmarshal(m, b)
}
func (m *HelloUltipaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloUltipaRequest.Marshal(b, m, deterministic)
}
func (m *HelloUltipaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloUltipaRequest.Merge(m, src)
}
func (m *HelloUltipaRequest) XXX_Size() int {
	return xxx_messageInfo_HelloUltipaRequest.Size(m)
}
func (m *HelloUltipaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloUltipaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloUltipaRequest proto.InternalMessageInfo

func (m *HelloUltipaRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type HelloUltipaReply struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloUltipaReply) Reset()         { *m = HelloUltipaReply{} }
func (m *HelloUltipaReply) String() string { return proto.CompactTextString(m) }
func (*HelloUltipaReply) ProtoMessage()    {}
func (*HelloUltipaReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cb30324c7364683, []int{1}
}

func (m *HelloUltipaReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloUltipaReply.Unmarshal(m, b)
}
func (m *HelloUltipaReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloUltipaReply.Marshal(b, m, deterministic)
}
func (m *HelloUltipaReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloUltipaReply.Merge(m, src)
}
func (m *HelloUltipaReply) XXX_Size() int {
	return xxx_messageInfo_HelloUltipaReply.Size(m)
}
func (m *HelloUltipaReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloUltipaReply.DiscardUnknown(m)
}

var xxx_messageInfo_HelloUltipaReply proto.InternalMessageInfo

func (m *HelloUltipaReply) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *HelloUltipaReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

//
//uql : ab.src(1).dest(2).depth(1).limit(10).select(*)
//db_name : default
//timeout  1s 单位:秒
type UqlRequest struct {
	Uql                  string   `protobuf:"bytes,1,opt,name=uql,proto3" json:"uql,omitempty"`
	Timeout              uint32   `protobuf:"varint,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	GraphName            string   `protobuf:"bytes,3,opt,name=graph_name,json=graphName,proto3" json:"graph_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UqlRequest) Reset()         { *m = UqlRequest{} }
func (m *UqlRequest) String() string { return proto.CompactTextString(m) }
func (*UqlRequest) ProtoMessage()    {}
func (*UqlRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cb30324c7364683, []int{2}
}

func (m *UqlRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UqlRequest.Unmarshal(m, b)
}
func (m *UqlRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UqlRequest.Marshal(b, m, deterministic)
}
func (m *UqlRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UqlRequest.Merge(m, src)
}
func (m *UqlRequest) XXX_Size() int {
	return xxx_messageInfo_UqlRequest.Size(m)
}
func (m *UqlRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UqlRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UqlRequest proto.InternalMessageInfo

func (m *UqlRequest) GetUql() string {
	if m != nil {
		return m.Uql
	}
	return ""
}

func (m *UqlRequest) GetTimeout() uint32 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *UqlRequest) GetGraphName() string {
	if m != nil {
		return m.GraphName
	}
	return ""
}

type UqlReply struct {
	Status               *Status      `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	TotalTimeCost        int32        `protobuf:"varint,3,opt,name=total_time_cost,json=totalTimeCost,proto3" json:"total_time_cost,omitempty"`
	EngineTimeCost       int32        `protobuf:"varint,4,opt,name=engine_time_cost,json=engineTimeCost,proto3" json:"engine_time_cost,omitempty"`
	Paths                []*Path      `protobuf:"bytes,5,rep,name=paths,proto3" json:"paths,omitempty"`
	Nodes                []*NodeAlias `protobuf:"bytes,6,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Edges                []*EdgeAlias `protobuf:"bytes,7,rep,name=edges,proto3" json:"edges,omitempty"`
	Attrs                []*AttrAlias `protobuf:"bytes,8,rep,name=attrs,proto3" json:"attrs,omitempty"`
	Tables               []*Table     `protobuf:"bytes,9,rep,name=tables,proto3" json:"tables,omitempty"`
	KeyValues            []*Value     `protobuf:"bytes,10,rep,name=key_values,json=keyValues,proto3" json:"key_values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *UqlReply) Reset()         { *m = UqlReply{} }
func (m *UqlReply) String() string { return proto.CompactTextString(m) }
func (*UqlReply) ProtoMessage()    {}
func (*UqlReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cb30324c7364683, []int{3}
}

func (m *UqlReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UqlReply.Unmarshal(m, b)
}
func (m *UqlReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UqlReply.Marshal(b, m, deterministic)
}
func (m *UqlReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UqlReply.Merge(m, src)
}
func (m *UqlReply) XXX_Size() int {
	return xxx_messageInfo_UqlReply.Size(m)
}
func (m *UqlReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UqlReply.DiscardUnknown(m)
}

var xxx_messageInfo_UqlReply proto.InternalMessageInfo

func (m *UqlReply) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *UqlReply) GetTotalTimeCost() int32 {
	if m != nil {
		return m.TotalTimeCost
	}
	return 0
}

func (m *UqlReply) GetEngineTimeCost() int32 {
	if m != nil {
		return m.EngineTimeCost
	}
	return 0
}

func (m *UqlReply) GetPaths() []*Path {
	if m != nil {
		return m.Paths
	}
	return nil
}

func (m *UqlReply) GetNodes() []*NodeAlias {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *UqlReply) GetEdges() []*EdgeAlias {
	if m != nil {
		return m.Edges
	}
	return nil
}

func (m *UqlReply) GetAttrs() []*AttrAlias {
	if m != nil {
		return m.Attrs
	}
	return nil
}

func (m *UqlReply) GetTables() []*Table {
	if m != nil {
		return m.Tables
	}
	return nil
}

func (m *UqlReply) GetKeyValues() []*Value {
	if m != nil {
		return m.KeyValues
	}
	return nil
}

type EdgeAlias struct {
	EdgeTable            *EdgeTable `protobuf:"bytes,1,opt,name=edge_table,json=edgeTable,proto3" json:"edge_table,omitempty"`
	Alias                string     `protobuf:"bytes,2,opt,name=alias,proto3" json:"alias,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *EdgeAlias) Reset()         { *m = EdgeAlias{} }
func (m *EdgeAlias) String() string { return proto.CompactTextString(m) }
func (*EdgeAlias) ProtoMessage()    {}
func (*EdgeAlias) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cb30324c7364683, []int{4}
}

func (m *EdgeAlias) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EdgeAlias.Unmarshal(m, b)
}
func (m *EdgeAlias) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EdgeAlias.Marshal(b, m, deterministic)
}
func (m *EdgeAlias) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EdgeAlias.Merge(m, src)
}
func (m *EdgeAlias) XXX_Size() int {
	return xxx_messageInfo_EdgeAlias.Size(m)
}
func (m *EdgeAlias) XXX_DiscardUnknown() {
	xxx_messageInfo_EdgeAlias.DiscardUnknown(m)
}

var xxx_messageInfo_EdgeAlias proto.InternalMessageInfo

func (m *EdgeAlias) GetEdgeTable() *EdgeTable {
	if m != nil {
		return m.EdgeTable
	}
	return nil
}

func (m *EdgeAlias) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

type NodeAlias struct {
	NodeTable            *NodeTable `protobuf:"bytes,1,opt,name=node_table,json=nodeTable,proto3" json:"node_table,omitempty"`
	Alias                string     `protobuf:"bytes,2,opt,name=alias,proto3" json:"alias,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *NodeAlias) Reset()         { *m = NodeAlias{} }
func (m *NodeAlias) String() string { return proto.CompactTextString(m) }
func (*NodeAlias) ProtoMessage()    {}
func (*NodeAlias) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cb30324c7364683, []int{5}
}

func (m *NodeAlias) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeAlias.Unmarshal(m, b)
}
func (m *NodeAlias) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeAlias.Marshal(b, m, deterministic)
}
func (m *NodeAlias) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeAlias.Merge(m, src)
}
func (m *NodeAlias) XXX_Size() int {
	return xxx_messageInfo_NodeAlias.Size(m)
}
func (m *NodeAlias) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeAlias.DiscardUnknown(m)
}

var xxx_messageInfo_NodeAlias proto.InternalMessageInfo

func (m *NodeAlias) GetNodeTable() *NodeTable {
	if m != nil {
		return m.NodeTable
	}
	return nil
}

func (m *NodeAlias) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

//key = alias.name, value = ly
type AttrAlias struct {
	Alias                string             `protobuf:"bytes,1,opt,name=alias,proto3" json:"alias,omitempty"`
	PropertyType         UltipaPropertyType `protobuf:"varint,2,opt,name=property_type,json=propertyType,proto3,enum=ultipa.UltipaPropertyType" json:"property_type,omitempty"`
	Values               [][]byte           `protobuf:"bytes,3,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *AttrAlias) Reset()         { *m = AttrAlias{} }
func (m *AttrAlias) String() string { return proto.CompactTextString(m) }
func (*AttrAlias) ProtoMessage()    {}
func (*AttrAlias) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cb30324c7364683, []int{6}
}

func (m *AttrAlias) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttrAlias.Unmarshal(m, b)
}
func (m *AttrAlias) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttrAlias.Marshal(b, m, deterministic)
}
func (m *AttrAlias) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttrAlias.Merge(m, src)
}
func (m *AttrAlias) XXX_Size() int {
	return xxx_messageInfo_AttrAlias.Size(m)
}
func (m *AttrAlias) XXX_DiscardUnknown() {
	xxx_messageInfo_AttrAlias.DiscardUnknown(m)
}

var xxx_messageInfo_AttrAlias proto.InternalMessageInfo

func (m *AttrAlias) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

func (m *AttrAlias) GetPropertyType() UltipaPropertyType {
	if m != nil {
		return m.PropertyType
	}
	return UltipaPropertyType_PROPERTY_INT32
}

func (m *AttrAlias) GetValues() [][]byte {
	if m != nil {
		return m.Values
	}
	return nil
}

//------------------------3.UserSetting------------------------------
type UserSettingRequest struct {
	UserName string                    `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Opt      UserSettingRequest_OPTION `protobuf:"varint,2,opt,name=opt,proto3,enum=ultipa.UserSettingRequest_OPTION" json:"opt,omitempty"`
	//key
	Type string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	//value
	Data                 string   `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserSettingRequest) Reset()         { *m = UserSettingRequest{} }
func (m *UserSettingRequest) String() string { return proto.CompactTextString(m) }
func (*UserSettingRequest) ProtoMessage()    {}
func (*UserSettingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cb30324c7364683, []int{7}
}

func (m *UserSettingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserSettingRequest.Unmarshal(m, b)
}
func (m *UserSettingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserSettingRequest.Marshal(b, m, deterministic)
}
func (m *UserSettingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserSettingRequest.Merge(m, src)
}
func (m *UserSettingRequest) XXX_Size() int {
	return xxx_messageInfo_UserSettingRequest.Size(m)
}
func (m *UserSettingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserSettingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserSettingRequest proto.InternalMessageInfo

func (m *UserSettingRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *UserSettingRequest) GetOpt() UserSettingRequest_OPTION {
	if m != nil {
		return m.Opt
	}
	return UserSettingRequest_OPT_GET
}

func (m *UserSettingRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *UserSettingRequest) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type UserSettingReply struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Data                 string   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserSettingReply) Reset()         { *m = UserSettingReply{} }
func (m *UserSettingReply) String() string { return proto.CompactTextString(m) }
func (*UserSettingReply) ProtoMessage()    {}
func (*UserSettingReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cb30324c7364683, []int{8}
}

func (m *UserSettingReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserSettingReply.Unmarshal(m, b)
}
func (m *UserSettingReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserSettingReply.Marshal(b, m, deterministic)
}
func (m *UserSettingReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserSettingReply.Merge(m, src)
}
func (m *UserSettingReply) XXX_Size() int {
	return xxx_messageInfo_UserSettingReply.Size(m)
}
func (m *UserSettingReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UserSettingReply.DiscardUnknown(m)
}

var xxx_messageInfo_UserSettingReply proto.InternalMessageInfo

func (m *UserSettingReply) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *UserSettingReply) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

//下载算法生成文件
type DownloadFileRequest struct {
	FilePathName         string   `protobuf:"bytes,1,opt,name=file_path_name,json=filePathName,proto3" json:"file_path_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DownloadFileRequest) Reset()         { *m = DownloadFileRequest{} }
func (m *DownloadFileRequest) String() string { return proto.CompactTextString(m) }
func (*DownloadFileRequest) ProtoMessage()    {}
func (*DownloadFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cb30324c7364683, []int{9}
}

func (m *DownloadFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownloadFileRequest.Unmarshal(m, b)
}
func (m *DownloadFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownloadFileRequest.Marshal(b, m, deterministic)
}
func (m *DownloadFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownloadFileRequest.Merge(m, src)
}
func (m *DownloadFileRequest) XXX_Size() int {
	return xxx_messageInfo_DownloadFileRequest.Size(m)
}
func (m *DownloadFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DownloadFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DownloadFileRequest proto.InternalMessageInfo

func (m *DownloadFileRequest) GetFilePathName() string {
	if m != nil {
		return m.FilePathName
	}
	return ""
}

type DownloadFileReply struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	TotalSize            int32    `protobuf:"varint,2,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	Chunk                []byte   `protobuf:"bytes,3,opt,name=chunk,proto3" json:"chunk,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DownloadFileReply) Reset()         { *m = DownloadFileReply{} }
func (m *DownloadFileReply) String() string { return proto.CompactTextString(m) }
func (*DownloadFileReply) ProtoMessage()    {}
func (*DownloadFileReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cb30324c7364683, []int{10}
}

func (m *DownloadFileReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownloadFileReply.Unmarshal(m, b)
}
func (m *DownloadFileReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownloadFileReply.Marshal(b, m, deterministic)
}
func (m *DownloadFileReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownloadFileReply.Merge(m, src)
}
func (m *DownloadFileReply) XXX_Size() int {
	return xxx_messageInfo_DownloadFileReply.Size(m)
}
func (m *DownloadFileReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DownloadFileReply.DiscardUnknown(m)
}

var xxx_messageInfo_DownloadFileReply proto.InternalMessageInfo

func (m *DownloadFileReply) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *DownloadFileReply) GetTotalSize() int32 {
	if m != nil {
		return m.TotalSize
	}
	return 0
}

func (m *DownloadFileReply) GetChunk() []byte {
	if m != nil {
		return m.Chunk
	}
	return nil
}

//导出数据
//limit <= 0 全量导出
type ExportRequest struct {
	DbType               DBType   `protobuf:"varint,1,opt,name=db_type,json=dbType,proto3,enum=ultipa.DBType" json:"db_type,omitempty"`
	Limit                int32    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	SelectProperties     []string `protobuf:"bytes,3,rep,name=select_properties,json=selectProperties,proto3" json:"select_properties,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExportRequest) Reset()         { *m = ExportRequest{} }
func (m *ExportRequest) String() string { return proto.CompactTextString(m) }
func (*ExportRequest) ProtoMessage()    {}
func (*ExportRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cb30324c7364683, []int{11}
}

func (m *ExportRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExportRequest.Unmarshal(m, b)
}
func (m *ExportRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExportRequest.Marshal(b, m, deterministic)
}
func (m *ExportRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExportRequest.Merge(m, src)
}
func (m *ExportRequest) XXX_Size() int {
	return xxx_messageInfo_ExportRequest.Size(m)
}
func (m *ExportRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExportRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExportRequest proto.InternalMessageInfo

func (m *ExportRequest) GetDbType() DBType {
	if m != nil {
		return m.DbType
	}
	return DBType_DBNODE
}

func (m *ExportRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ExportRequest) GetSelectProperties() []string {
	if m != nil {
		return m.SelectProperties
	}
	return nil
}

type ExportReply struct {
	Status               *Status    `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	NodeTable            *NodeTable `protobuf:"bytes,2,opt,name=node_table,json=nodeTable,proto3" json:"node_table,omitempty"`
	EdgeTable            *EdgeTable `protobuf:"bytes,3,opt,name=edge_table,json=edgeTable,proto3" json:"edge_table,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ExportReply) Reset()         { *m = ExportReply{} }
func (m *ExportReply) String() string { return proto.CompactTextString(m) }
func (*ExportReply) ProtoMessage()    {}
func (*ExportReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cb30324c7364683, []int{12}
}

func (m *ExportReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExportReply.Unmarshal(m, b)
}
func (m *ExportReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExportReply.Marshal(b, m, deterministic)
}
func (m *ExportReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExportReply.Merge(m, src)
}
func (m *ExportReply) XXX_Size() int {
	return xxx_messageInfo_ExportReply.Size(m)
}
func (m *ExportReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ExportReply.DiscardUnknown(m)
}

var xxx_messageInfo_ExportReply proto.InternalMessageInfo

func (m *ExportReply) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ExportReply) GetNodeTable() *NodeTable {
	if m != nil {
		return m.NodeTable
	}
	return nil
}

func (m *ExportReply) GetEdgeTable() *EdgeTable {
	if m != nil {
		return m.EdgeTable
	}
	return nil
}

//------------------------6.GetLeader------------------------------
type GetLeaderRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetLeaderRequest) Reset()         { *m = GetLeaderRequest{} }
func (m *GetLeaderRequest) String() string { return proto.CompactTextString(m) }
func (*GetLeaderRequest) ProtoMessage()    {}
func (*GetLeaderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cb30324c7364683, []int{13}
}

func (m *GetLeaderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLeaderRequest.Unmarshal(m, b)
}
func (m *GetLeaderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLeaderRequest.Marshal(b, m, deterministic)
}
func (m *GetLeaderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLeaderRequest.Merge(m, src)
}
func (m *GetLeaderRequest) XXX_Size() int {
	return xxx_messageInfo_GetLeaderRequest.Size(m)
}
func (m *GetLeaderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLeaderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetLeaderRequest proto.InternalMessageInfo

type GetLeaderReply struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetLeaderReply) Reset()         { *m = GetLeaderReply{} }
func (m *GetLeaderReply) String() string { return proto.CompactTextString(m) }
func (*GetLeaderReply) ProtoMessage()    {}
func (*GetLeaderReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cb30324c7364683, []int{14}
}

func (m *GetLeaderReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLeaderReply.Unmarshal(m, b)
}
func (m *GetLeaderReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLeaderReply.Marshal(b, m, deterministic)
}
func (m *GetLeaderReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLeaderReply.Merge(m, src)
}
func (m *GetLeaderReply) XXX_Size() int {
	return xxx_messageInfo_GetLeaderReply.Size(m)
}
func (m *GetLeaderReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLeaderReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetLeaderReply proto.InternalMessageInfo

func (m *GetLeaderReply) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

//------------------------7.InsertNodes------------------------------
type InsertNodesRequest struct {
	NodeTable *NodeTable `protobuf:"bytes,1,opt,name=node_table,json=nodeTable,proto3" json:"node_table,omitempty"`
	//if true return ids
	Silent               bool     `protobuf:"varint,2,opt,name=silent,proto3" json:"silent,omitempty"`
	NoInnerId            bool     `protobuf:"varint,3,opt,name=no_inner_id,json=noInnerId,proto3" json:"no_inner_id,omitempty"`
	GraphName            string   `protobuf:"bytes,4,opt,name=graph_name,json=graphName,proto3" json:"graph_name,omitempty"`
	CheckO               bool     `protobuf:"varint,5,opt,name=check_o,json=checkO,proto3" json:"check_o,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InsertNodesRequest) Reset()         { *m = InsertNodesRequest{} }
func (m *InsertNodesRequest) String() string { return proto.CompactTextString(m) }
func (*InsertNodesRequest) ProtoMessage()    {}
func (*InsertNodesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cb30324c7364683, []int{15}
}

func (m *InsertNodesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InsertNodesRequest.Unmarshal(m, b)
}
func (m *InsertNodesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InsertNodesRequest.Marshal(b, m, deterministic)
}
func (m *InsertNodesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InsertNodesRequest.Merge(m, src)
}
func (m *InsertNodesRequest) XXX_Size() int {
	return xxx_messageInfo_InsertNodesRequest.Size(m)
}
func (m *InsertNodesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InsertNodesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InsertNodesRequest proto.InternalMessageInfo

func (m *InsertNodesRequest) GetNodeTable() *NodeTable {
	if m != nil {
		return m.NodeTable
	}
	return nil
}

func (m *InsertNodesRequest) GetSilent() bool {
	if m != nil {
		return m.Silent
	}
	return false
}

func (m *InsertNodesRequest) GetNoInnerId() bool {
	if m != nil {
		return m.NoInnerId
	}
	return false
}

func (m *InsertNodesRequest) GetGraphName() string {
	if m != nil {
		return m.GraphName
	}
	return ""
}

func (m *InsertNodesRequest) GetCheckO() bool {
	if m != nil {
		return m.CheckO
	}
	return false
}

type InsertNodesReply struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	TimeCost             int32    `protobuf:"varint,2,opt,name=time_cost,json=timeCost,proto3" json:"time_cost,omitempty"`
	EngineTimeCost       int32    `protobuf:"varint,3,opt,name=engine_time_cost,json=engineTimeCost,proto3" json:"engine_time_cost,omitempty"`
	Ids                  []int64  `protobuf:"varint,4,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	IgnoreIndexes        []int32  `protobuf:"varint,5,rep,packed,name=ignore_indexes,json=ignoreIndexes,proto3" json:"ignore_indexes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InsertNodesReply) Reset()         { *m = InsertNodesReply{} }
func (m *InsertNodesReply) String() string { return proto.CompactTextString(m) }
func (*InsertNodesReply) ProtoMessage()    {}
func (*InsertNodesReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cb30324c7364683, []int{16}
}

func (m *InsertNodesReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InsertNodesReply.Unmarshal(m, b)
}
func (m *InsertNodesReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InsertNodesReply.Marshal(b, m, deterministic)
}
func (m *InsertNodesReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InsertNodesReply.Merge(m, src)
}
func (m *InsertNodesReply) XXX_Size() int {
	return xxx_messageInfo_InsertNodesReply.Size(m)
}
func (m *InsertNodesReply) XXX_DiscardUnknown() {
	xxx_messageInfo_InsertNodesReply.DiscardUnknown(m)
}

var xxx_messageInfo_InsertNodesReply proto.InternalMessageInfo

func (m *InsertNodesReply) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *InsertNodesReply) GetTimeCost() int32 {
	if m != nil {
		return m.TimeCost
	}
	return 0
}

func (m *InsertNodesReply) GetEngineTimeCost() int32 {
	if m != nil {
		return m.EngineTimeCost
	}
	return 0
}

func (m *InsertNodesReply) GetIds() []int64 {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (m *InsertNodesReply) GetIgnoreIndexes() []int32 {
	if m != nil {
		return m.IgnoreIndexes
	}
	return nil
}

//------------------------8.InsertEdges------------------------------
type InsertEdgesRequest struct {
	EdgeTable *EdgeTable `protobuf:"bytes,1,opt,name=edge_table,json=edgeTable,proto3" json:"edge_table,omitempty"`
	//if true return ids
	Silent               bool     `protobuf:"varint,2,opt,name=silent,proto3" json:"silent,omitempty"`
	NoInnerId            bool     `protobuf:"varint,3,opt,name=no_inner_id,json=noInnerId,proto3" json:"no_inner_id,omitempty"`
	GraphName            string   `protobuf:"bytes,4,opt,name=graph_name,json=graphName,proto3" json:"graph_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InsertEdgesRequest) Reset()         { *m = InsertEdgesRequest{} }
func (m *InsertEdgesRequest) String() string { return proto.CompactTextString(m) }
func (*InsertEdgesRequest) ProtoMessage()    {}
func (*InsertEdgesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cb30324c7364683, []int{17}
}

func (m *InsertEdgesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InsertEdgesRequest.Unmarshal(m, b)
}
func (m *InsertEdgesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InsertEdgesRequest.Marshal(b, m, deterministic)
}
func (m *InsertEdgesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InsertEdgesRequest.Merge(m, src)
}
func (m *InsertEdgesRequest) XXX_Size() int {
	return xxx_messageInfo_InsertEdgesRequest.Size(m)
}
func (m *InsertEdgesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InsertEdgesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InsertEdgesRequest proto.InternalMessageInfo

func (m *InsertEdgesRequest) GetEdgeTable() *EdgeTable {
	if m != nil {
		return m.EdgeTable
	}
	return nil
}

func (m *InsertEdgesRequest) GetSilent() bool {
	if m != nil {
		return m.Silent
	}
	return false
}

func (m *InsertEdgesRequest) GetNoInnerId() bool {
	if m != nil {
		return m.NoInnerId
	}
	return false
}

func (m *InsertEdgesRequest) GetGraphName() string {
	if m != nil {
		return m.GraphName
	}
	return ""
}

type InsertEdgesReply struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	TimeCost             int32    `protobuf:"varint,2,opt,name=time_cost,json=timeCost,proto3" json:"time_cost,omitempty"`
	EngineTimeCost       int32    `protobuf:"varint,3,opt,name=engine_time_cost,json=engineTimeCost,proto3" json:"engine_time_cost,omitempty"`
	Ids                  []int64  `protobuf:"varint,4,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	IgnoreIndexes        []int32  `protobuf:"varint,5,rep,packed,name=ignore_indexes,json=ignoreIndexes,proto3" json:"ignore_indexes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InsertEdgesReply) Reset()         { *m = InsertEdgesReply{} }
func (m *InsertEdgesReply) String() string { return proto.CompactTextString(m) }
func (*InsertEdgesReply) ProtoMessage()    {}
func (*InsertEdgesReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cb30324c7364683, []int{18}
}

func (m *InsertEdgesReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InsertEdgesReply.Unmarshal(m, b)
}
func (m *InsertEdgesReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InsertEdgesReply.Marshal(b, m, deterministic)
}
func (m *InsertEdgesReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InsertEdgesReply.Merge(m, src)
}
func (m *InsertEdgesReply) XXX_Size() int {
	return xxx_messageInfo_InsertEdgesReply.Size(m)
}
func (m *InsertEdgesReply) XXX_DiscardUnknown() {
	xxx_messageInfo_InsertEdgesReply.DiscardUnknown(m)
}

var xxx_messageInfo_InsertEdgesReply proto.InternalMessageInfo

func (m *InsertEdgesReply) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *InsertEdgesReply) GetTimeCost() int32 {
	if m != nil {
		return m.TimeCost
	}
	return 0
}

func (m *InsertEdgesReply) GetEngineTimeCost() int32 {
	if m != nil {
		return m.EngineTimeCost
	}
	return 0
}

func (m *InsertEdgesReply) GetIds() []int64 {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (m *InsertEdgesReply) GetIgnoreIndexes() []int32 {
	if m != nil {
		return m.IgnoreIndexes
	}
	return nil
}

type Status struct {
	ErrorCode            ErrorCode    `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3,enum=ultipa.ErrorCode" json:"error_code,omitempty"`
	Msg                  string       `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	ClusterInfo          *ClusterInfo `protobuf:"bytes,3,opt,name=cluster_info,json=clusterInfo,proto3" json:"cluster_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cb30324c7364683, []int{19}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetErrorCode() ErrorCode {
	if m != nil {
		return m.ErrorCode
	}
	return ErrorCode_SUCCESS
}

func (m *Status) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *Status) GetClusterInfo() *ClusterInfo {
	if m != nil {
		return m.ClusterInfo
	}
	return nil
}

type RaftFollower struct {
	Address              string       `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Role                 int32        `protobuf:"varint,2,opt,name=role,proto3" json:"role,omitempty"`
	Status               ServerStatus `protobuf:"varint,3,opt,name=status,proto3,enum=ultipa.ServerStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *RaftFollower) Reset()         { *m = RaftFollower{} }
func (m *RaftFollower) String() string { return proto.CompactTextString(m) }
func (*RaftFollower) ProtoMessage()    {}
func (*RaftFollower) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cb30324c7364683, []int{20}
}

func (m *RaftFollower) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RaftFollower.Unmarshal(m, b)
}
func (m *RaftFollower) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RaftFollower.Marshal(b, m, deterministic)
}
func (m *RaftFollower) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RaftFollower.Merge(m, src)
}
func (m *RaftFollower) XXX_Size() int {
	return xxx_messageInfo_RaftFollower.Size(m)
}
func (m *RaftFollower) XXX_DiscardUnknown() {
	xxx_messageInfo_RaftFollower.DiscardUnknown(m)
}

var xxx_messageInfo_RaftFollower proto.InternalMessageInfo

func (m *RaftFollower) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *RaftFollower) GetRole() int32 {
	if m != nil {
		return m.Role
	}
	return 0
}

func (m *RaftFollower) GetStatus() ServerStatus {
	if m != nil {
		return m.Status
	}
	return ServerStatus_DEAD
}

type ClusterInfo struct {
	Redirect             string          `protobuf:"bytes,1,opt,name=redirect,proto3" json:"redirect,omitempty"`
	LeaderAddress        string          `protobuf:"bytes,2,opt,name=leader_address,json=leaderAddress,proto3" json:"leader_address,omitempty"`
	Followers            []*RaftFollower `protobuf:"bytes,3,rep,name=followers,proto3" json:"followers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ClusterInfo) Reset()         { *m = ClusterInfo{} }
func (m *ClusterInfo) String() string { return proto.CompactTextString(m) }
func (*ClusterInfo) ProtoMessage()    {}
func (*ClusterInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cb30324c7364683, []int{21}
}

func (m *ClusterInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterInfo.Unmarshal(m, b)
}
func (m *ClusterInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterInfo.Marshal(b, m, deterministic)
}
func (m *ClusterInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterInfo.Merge(m, src)
}
func (m *ClusterInfo) XXX_Size() int {
	return xxx_messageInfo_ClusterInfo.Size(m)
}
func (m *ClusterInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterInfo proto.InternalMessageInfo

func (m *ClusterInfo) GetRedirect() string {
	if m != nil {
		return m.Redirect
	}
	return ""
}

func (m *ClusterInfo) GetLeaderAddress() string {
	if m != nil {
		return m.LeaderAddress
	}
	return ""
}

func (m *ClusterInfo) GetFollowers() []*RaftFollower {
	if m != nil {
		return m.Followers
	}
	return nil
}

type Path struct {
	NodeTable            *NodeTable `protobuf:"bytes,1,opt,name=node_table,json=nodeTable,proto3" json:"node_table,omitempty"`
	EdgeTable            *EdgeTable `protobuf:"bytes,2,opt,name=edge_table,json=edgeTable,proto3" json:"edge_table,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Path) Reset()         { *m = Path{} }
func (m *Path) String() string { return proto.CompactTextString(m) }
func (*Path) ProtoMessage()    {}
func (*Path) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cb30324c7364683, []int{22}
}

func (m *Path) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Path.Unmarshal(m, b)
}
func (m *Path) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Path.Marshal(b, m, deterministic)
}
func (m *Path) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Path.Merge(m, src)
}
func (m *Path) XXX_Size() int {
	return xxx_messageInfo_Path.Size(m)
}
func (m *Path) XXX_DiscardUnknown() {
	xxx_messageInfo_Path.DiscardUnknown(m)
}

var xxx_messageInfo_Path proto.InternalMessageInfo

func (m *Path) GetNodeTable() *NodeTable {
	if m != nil {
		return m.NodeTable
	}
	return nil
}

func (m *Path) GetEdgeTable() *EdgeTable {
	if m != nil {
		return m.EdgeTable
	}
	return nil
}

type Table struct {
	TableName            string      `protobuf:"bytes,1,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	Headers              []string    `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty"`
	TableRows            []*TableRow `protobuf:"bytes,3,rep,name=table_rows,json=tableRows,proto3" json:"table_rows,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Table) Reset()         { *m = Table{} }
func (m *Table) String() string { return proto.CompactTextString(m) }
func (*Table) ProtoMessage()    {}
func (*Table) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cb30324c7364683, []int{23}
}

func (m *Table) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Table.Unmarshal(m, b)
}
func (m *Table) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Table.Marshal(b, m, deterministic)
}
func (m *Table) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Table.Merge(m, src)
}
func (m *Table) XXX_Size() int {
	return xxx_messageInfo_Table.Size(m)
}
func (m *Table) XXX_DiscardUnknown() {
	xxx_messageInfo_Table.DiscardUnknown(m)
}

var xxx_messageInfo_Table proto.InternalMessageInfo

func (m *Table) GetTableName() string {
	if m != nil {
		return m.TableName
	}
	return ""
}

func (m *Table) GetHeaders() []string {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *Table) GetTableRows() []*TableRow {
	if m != nil {
		return m.TableRows
	}
	return nil
}

type TableRow struct {
	Values               [][]byte `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TableRow) Reset()         { *m = TableRow{} }
func (m *TableRow) String() string { return proto.CompactTextString(m) }
func (*TableRow) ProtoMessage()    {}
func (*TableRow) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cb30324c7364683, []int{24}
}

func (m *TableRow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TableRow.Unmarshal(m, b)
}
func (m *TableRow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TableRow.Marshal(b, m, deterministic)
}
func (m *TableRow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TableRow.Merge(m, src)
}
func (m *TableRow) XXX_Size() int {
	return xxx_messageInfo_TableRow.Size(m)
}
func (m *TableRow) XXX_DiscardUnknown() {
	xxx_messageInfo_TableRow.DiscardUnknown(m)
}

var xxx_messageInfo_TableRow proto.InternalMessageInfo

func (m *TableRow) GetValues() [][]byte {
	if m != nil {
		return m.Values
	}
	return nil
}

type NodeTable struct {
	Headers              []*Header  `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty"`
	NodeRows             []*NodeRow `protobuf:"bytes,3,rep,name=node_rows,json=nodeRows,proto3" json:"node_rows,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *NodeTable) Reset()         { *m = NodeTable{} }
func (m *NodeTable) String() string { return proto.CompactTextString(m) }
func (*NodeTable) ProtoMessage()    {}
func (*NodeTable) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cb30324c7364683, []int{25}
}

func (m *NodeTable) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeTable.Unmarshal(m, b)
}
func (m *NodeTable) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeTable.Marshal(b, m, deterministic)
}
func (m *NodeTable) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeTable.Merge(m, src)
}
func (m *NodeTable) XXX_Size() int {
	return xxx_messageInfo_NodeTable.Size(m)
}
func (m *NodeTable) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeTable.DiscardUnknown(m)
}

var xxx_messageInfo_NodeTable proto.InternalMessageInfo

func (m *NodeTable) GetHeaders() []*Header {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *NodeTable) GetNodeRows() []*NodeRow {
	if m != nil {
		return m.NodeRows
	}
	return nil
}

type EdgeTable struct {
	Headers              []*Header  `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty"`
	EdgeRows             []*EdgeRow `protobuf:"bytes,3,rep,name=edge_rows,json=edgeRows,proto3" json:"edge_rows,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *EdgeTable) Reset()         { *m = EdgeTable{} }
func (m *EdgeTable) String() string { return proto.CompactTextString(m) }
func (*EdgeTable) ProtoMessage()    {}
func (*EdgeTable) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cb30324c7364683, []int{26}
}

func (m *EdgeTable) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EdgeTable.Unmarshal(m, b)
}
func (m *EdgeTable) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EdgeTable.Marshal(b, m, deterministic)
}
func (m *EdgeTable) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EdgeTable.Merge(m, src)
}
func (m *EdgeTable) XXX_Size() int {
	return xxx_messageInfo_EdgeTable.Size(m)
}
func (m *EdgeTable) XXX_DiscardUnknown() {
	xxx_messageInfo_EdgeTable.DiscardUnknown(m)
}

var xxx_messageInfo_EdgeTable proto.InternalMessageInfo

func (m *EdgeTable) GetHeaders() []*Header {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *EdgeTable) GetEdgeRows() []*EdgeRow {
	if m != nil {
		return m.EdgeRows
	}
	return nil
}

type NodeRow struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Values               [][]byte `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeRow) Reset()         { *m = NodeRow{} }
func (m *NodeRow) String() string { return proto.CompactTextString(m) }
func (*NodeRow) ProtoMessage()    {}
func (*NodeRow) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cb30324c7364683, []int{27}
}

func (m *NodeRow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeRow.Unmarshal(m, b)
}
func (m *NodeRow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeRow.Marshal(b, m, deterministic)
}
func (m *NodeRow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeRow.Merge(m, src)
}
func (m *NodeRow) XXX_Size() int {
	return xxx_messageInfo_NodeRow.Size(m)
}
func (m *NodeRow) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeRow.DiscardUnknown(m)
}

var xxx_messageInfo_NodeRow proto.InternalMessageInfo

func (m *NodeRow) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *NodeRow) GetValues() [][]byte {
	if m != nil {
		return m.Values
	}
	return nil
}

type EdgeRow struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FromId               int64    `protobuf:"varint,2,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	ToId                 int64    `protobuf:"varint,3,opt,name=to_id,json=toId,proto3" json:"to_id,omitempty"`
	Values               [][]byte `protobuf:"bytes,4,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EdgeRow) Reset()         { *m = EdgeRow{} }
func (m *EdgeRow) String() string { return proto.CompactTextString(m) }
func (*EdgeRow) ProtoMessage()    {}
func (*EdgeRow) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cb30324c7364683, []int{28}
}

func (m *EdgeRow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EdgeRow.Unmarshal(m, b)
}
func (m *EdgeRow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EdgeRow.Marshal(b, m, deterministic)
}
func (m *EdgeRow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EdgeRow.Merge(m, src)
}
func (m *EdgeRow) XXX_Size() int {
	return xxx_messageInfo_EdgeRow.Size(m)
}
func (m *EdgeRow) XXX_DiscardUnknown() {
	xxx_messageInfo_EdgeRow.DiscardUnknown(m)
}

var xxx_messageInfo_EdgeRow proto.InternalMessageInfo

func (m *EdgeRow) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *EdgeRow) GetFromId() int64 {
	if m != nil {
		return m.FromId
	}
	return 0
}

func (m *EdgeRow) GetToId() int64 {
	if m != nil {
		return m.ToId
	}
	return 0
}

func (m *EdgeRow) GetValues() [][]byte {
	if m != nil {
		return m.Values
	}
	return nil
}

type Header struct {
	PropertyName         string             `protobuf:"bytes,1,opt,name=property_name,json=propertyName,proto3" json:"property_name,omitempty"`
	PropertyType         UltipaPropertyType `protobuf:"varint,2,opt,name=property_type,json=propertyType,proto3,enum=ultipa.UltipaPropertyType" json:"property_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Header) Reset()         { *m = Header{} }
func (m *Header) String() string { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()    {}
func (*Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cb30324c7364683, []int{29}
}

func (m *Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Header.Unmarshal(m, b)
}
func (m *Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Header.Marshal(b, m, deterministic)
}
func (m *Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Header.Merge(m, src)
}
func (m *Header) XXX_Size() int {
	return xxx_messageInfo_Header.Size(m)
}
func (m *Header) XXX_DiscardUnknown() {
	xxx_messageInfo_Header.DiscardUnknown(m)
}

var xxx_messageInfo_Header proto.InternalMessageInfo

func (m *Header) GetPropertyName() string {
	if m != nil {
		return m.PropertyName
	}
	return ""
}

func (m *Header) GetPropertyType() UltipaPropertyType {
	if m != nil {
		return m.PropertyType
	}
	return UltipaPropertyType_PROPERTY_INT32
}

type Value struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Value) Reset()         { *m = Value{} }
func (m *Value) String() string { return proto.CompactTextString(m) }
func (*Value) ProtoMessage()    {}
func (*Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cb30324c7364683, []int{30}
}

func (m *Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Value.Unmarshal(m, b)
}
func (m *Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Value.Marshal(b, m, deterministic)
}
func (m *Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Value.Merge(m, src)
}
func (m *Value) XXX_Size() int {
	return xxx_messageInfo_Value.Size(m)
}
func (m *Value) XXX_DiscardUnknown() {
	xxx_messageInfo_Value.DiscardUnknown(m)
}

var xxx_messageInfo_Value proto.InternalMessageInfo

func (m *Value) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Value) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterEnum("ultipa.UltipaPropertyType", UltipaPropertyType_name, UltipaPropertyType_value)
	proto.RegisterEnum("ultipa.ErrorCode", ErrorCode_name, ErrorCode_value)
	proto.RegisterEnum("ultipa.FollowerRole", FollowerRole_name, FollowerRole_value)
	proto.RegisterEnum("ultipa.ServerStatus", ServerStatus_name, ServerStatus_value)
	proto.RegisterEnum("ultipa.DBType", DBType_name, DBType_value)
	proto.RegisterEnum("ultipa.TASK_STATUS", TASK_STATUS_name, TASK_STATUS_value)
	proto.RegisterEnum("ultipa.UserSettingRequest_OPTION", UserSettingRequest_OPTION_name, UserSettingRequest_OPTION_value)
	proto.RegisterType((*HelloUltipaRequest)(nil), "ultipa.HelloUltipaRequest")
	proto.RegisterType((*HelloUltipaReply)(nil), "ultipa.HelloUltipaReply")
	proto.RegisterType((*UqlRequest)(nil), "ultipa.UqlRequest")
	proto.RegisterType((*UqlReply)(nil), "ultipa.UqlReply")
	proto.RegisterType((*EdgeAlias)(nil), "ultipa.EdgeAlias")
	proto.RegisterType((*NodeAlias)(nil), "ultipa.NodeAlias")
	proto.RegisterType((*AttrAlias)(nil), "ultipa.AttrAlias")
	proto.RegisterType((*UserSettingRequest)(nil), "ultipa.UserSettingRequest")
	proto.RegisterType((*UserSettingReply)(nil), "ultipa.UserSettingReply")
	proto.RegisterType((*DownloadFileRequest)(nil), "ultipa.DownloadFileRequest")
	proto.RegisterType((*DownloadFileReply)(nil), "ultipa.DownloadFileReply")
	proto.RegisterType((*ExportRequest)(nil), "ultipa.ExportRequest")
	proto.RegisterType((*ExportReply)(nil), "ultipa.ExportReply")
	proto.RegisterType((*GetLeaderRequest)(nil), "ultipa.GetLeaderRequest")
	proto.RegisterType((*GetLeaderReply)(nil), "ultipa.GetLeaderReply")
	proto.RegisterType((*InsertNodesRequest)(nil), "ultipa.InsertNodesRequest")
	proto.RegisterType((*InsertNodesReply)(nil), "ultipa.InsertNodesReply")
	proto.RegisterType((*InsertEdgesRequest)(nil), "ultipa.InsertEdgesRequest")
	proto.RegisterType((*InsertEdgesReply)(nil), "ultipa.InsertEdgesReply")
	proto.RegisterType((*Status)(nil), "ultipa.Status")
	proto.RegisterType((*RaftFollower)(nil), "ultipa.RaftFollower")
	proto.RegisterType((*ClusterInfo)(nil), "ultipa.ClusterInfo")
	proto.RegisterType((*Path)(nil), "ultipa.Path")
	proto.RegisterType((*Table)(nil), "ultipa.Table")
	proto.RegisterType((*TableRow)(nil), "ultipa.TableRow")
	proto.RegisterType((*NodeTable)(nil), "ultipa.NodeTable")
	proto.RegisterType((*EdgeTable)(nil), "ultipa.EdgeTable")
	proto.RegisterType((*NodeRow)(nil), "ultipa.NodeRow")
	proto.RegisterType((*EdgeRow)(nil), "ultipa.EdgeRow")
	proto.RegisterType((*Header)(nil), "ultipa.Header")
	proto.RegisterType((*Value)(nil), "ultipa.Value")
}

func init() { proto.RegisterFile("ultipa.proto", fileDescriptor_6cb30324c7364683) }

var fileDescriptor_6cb30324c7364683 = []byte{
	// 1876 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x58, 0x5f, 0x73, 0xdb, 0xc6,
	0x11, 0x17, 0xff, 0x13, 0x4b, 0x52, 0x82, 0x4e, 0x8e, 0xc3, 0xca, 0x93, 0x54, 0x45, 0x9a, 0x44,
	0xa3, 0x7a, 0xec, 0x44, 0xce, 0x78, 0x32, 0xd3, 0x87, 0x0c, 0x24, 0x9c, 0x14, 0xb4, 0x34, 0xc1,
	0x1e, 0x40, 0xbb, 0x7e, 0xe8, 0x60, 0x60, 0xe2, 0x24, 0x21, 0x82, 0x00, 0x0a, 0x80, 0x22, 0xd3,
	0x7d, 0xcd, 0x97, 0xe8, 0x43, 0xbf, 0x44, 0x1e, 0xda, 0x99, 0x7e, 0x8a, 0x7e, 0x9c, 0x3e, 0x76,
	0xee, 0x0e, 0x07, 0x02, 0x94, 0xda, 0x9a, 0xed, 0xf4, 0x21, 0x6f, 0xb7, 0xbf, 0xdb, 0xdb, 0xdd,
	0xfb, 0xe1, 0x76, 0x6f, 0x0f, 0xd0, 0xbf, 0x09, 0xb3, 0x60, 0xee, 0x3d, 0x99, 0x27, 0x71, 0x16,
	0xa3, 0xb6, 0x90, 0xb4, 0x7d, 0x40, 0xdf, 0xd2, 0x30, 0x8c, 0xa7, 0x5c, 0x24, 0xf4, 0xfa, 0x86,
	0xa6, 0x19, 0x42, 0xd0, 0x8c, 0xbc, 0x2b, 0x3a, 0xac, 0xed, 0xd5, 0xf6, 0x15, 0xc2, 0xc7, 0x9a,
	0x03, 0x6a, 0x45, 0x73, 0x1e, 0x2e, 0xd0, 0x67, 0xd0, 0x4e, 0x33, 0x2f, 0xbb, 0x49, 0xb9, 0x66,
	0xef, 0x70, 0xf3, 0x49, 0xee, 0xc4, 0xe6, 0x28, 0xc9, 0x67, 0xd1, 0x10, 0x3a, 0x57, 0x34, 0x4d,
	0xbd, 0x73, 0x3a, 0xac, 0x73, 0x93, 0x52, 0xd4, 0x5e, 0x01, 0x4c, 0xaf, 0x43, 0xe9, 0x57, 0x85,
	0xc6, 0xcd, 0x75, 0x98, 0xbb, 0x65, 0x43, 0xb6, 0x32, 0x0b, 0xae, 0x68, 0x7c, 0x93, 0xf1, 0x95,
	0x03, 0x22, 0x45, 0xf4, 0x11, 0xc0, 0x79, 0xe2, 0xcd, 0x2f, 0x5c, 0x1e, 0x69, 0x83, 0x2f, 0x51,
	0x38, 0x32, 0x66, 0xe1, 0xfe, 0xa3, 0x0e, 0x5d, 0x6e, 0x79, 0x9d, 0x38, 0x3f, 0x83, 0xad, 0x2c,
	0xce, 0xbc, 0xd0, 0x65, 0x4e, 0xdc, 0x59, 0x9c, 0x66, 0xdc, 0x70, 0x8b, 0x0c, 0x38, 0xec, 0x04,
	0x57, 0xf4, 0x38, 0x4e, 0x33, 0xb4, 0x0f, 0x2a, 0x8d, 0xce, 0x83, 0x88, 0x96, 0x14, 0x9b, 0x5c,
	0x71, 0x53, 0xe0, 0x85, 0xa6, 0x06, 0xad, 0xb9, 0x97, 0x5d, 0xa4, 0xc3, 0xd6, 0x5e, 0x63, 0xbf,
	0x77, 0xd8, 0x97, 0x8e, 0x27, 0x5e, 0x76, 0x41, 0xc4, 0x14, 0xfa, 0x1c, 0x5a, 0x51, 0xec, 0xd3,
	0x74, 0xd8, 0xe6, 0x3a, 0xdb, 0x52, 0x67, 0x1c, 0xfb, 0x54, 0x0f, 0x03, 0x2f, 0x25, 0x62, 0x9e,
	0x29, 0x52, 0xff, 0x9c, 0xa6, 0xc3, 0x4e, 0x55, 0x11, 0xfb, 0xe7, 0x52, 0x91, 0xcf, 0x33, 0x45,
	0x2f, 0xcb, 0x92, 0x74, 0xd8, 0xad, 0x2a, 0xea, 0x59, 0x96, 0xe4, 0x8a, 0x7c, 0x1e, 0x7d, 0x0a,
	0xed, 0xcc, 0x7b, 0x13, 0xd2, 0x74, 0xa8, 0x70, 0xcd, 0x81, 0xd4, 0x74, 0x18, 0x4a, 0xf2, 0x49,
	0xf4, 0x18, 0xe0, 0x92, 0x2e, 0xdc, 0xef, 0xbd, 0xf0, 0x86, 0xa6, 0x43, 0xa8, 0xaa, 0xbe, 0x64,
	0x28, 0x51, 0x2e, 0xe9, 0x82, 0x8f, 0x52, 0xcd, 0x06, 0xa5, 0x88, 0x08, 0x7d, 0x01, 0xc0, 0x62,
	0x72, 0xb9, 0xa5, 0x9c, 0xfe, 0x4a, 0xe0, 0xc2, 0x93, 0x42, 0xe5, 0x10, 0x3d, 0x80, 0x96, 0xc7,
	0x96, 0xe6, 0x47, 0x45, 0x08, 0xcc, 0x68, 0xc1, 0x07, 0x33, 0xca, 0x18, 0xb9, 0xdf, 0x28, 0x53,
	0xcb, 0x8d, 0x46, 0x72, 0xf8, 0x2f, 0x8c, 0xbe, 0x03, 0xa5, 0xa0, 0x64, 0xa9, 0x52, 0x2b, 0xa9,
	0xa0, 0x6f, 0x60, 0x30, 0x4f, 0xe2, 0x39, 0x4d, 0xb2, 0x85, 0x9b, 0x2d, 0xe6, 0xe2, 0x00, 0x6f,
	0x1e, 0xee, 0x4a, 0x6f, 0x22, 0x1d, 0x26, 0xb9, 0x8a, 0xb3, 0x98, 0x53, 0xd2, 0x9f, 0x97, 0x24,
	0xf4, 0x10, 0xda, 0x39, 0x6f, 0x8d, 0xbd, 0xc6, 0x7e, 0x9f, 0xe4, 0x92, 0xf6, 0x63, 0x0d, 0xd0,
	0x34, 0xa5, 0x89, 0x4d, 0xb3, 0x2c, 0x88, 0xce, 0x65, 0x0a, 0x3c, 0x02, 0xe5, 0x26, 0xa5, 0x89,
	0x5b, 0xca, 0xbf, 0x2e, 0x03, 0xd8, 0xa1, 0x46, 0xcf, 0xa0, 0x11, 0xcf, 0xb3, 0x3c, 0x84, 0x5f,
	0x14, 0x21, 0xdc, 0xb1, 0xf2, 0xc4, 0x9a, 0x38, 0xa6, 0x35, 0x26, 0x4c, 0x9b, 0x25, 0x33, 0x0f,
	0x5c, 0xa4, 0x08, 0x1f, 0x33, 0xcc, 0xf7, 0x32, 0x8f, 0x1f, 0x5a, 0x85, 0xf0, 0xb1, 0xa6, 0x41,
	0x5b, 0x2c, 0x43, 0x3d, 0xe8, 0x58, 0x13, 0xc7, 0x3d, 0xc5, 0x8e, 0xba, 0x21, 0x05, 0x1b, 0x3b,
	0x6a, 0x4d, 0x1b, 0x83, 0x5a, 0xf1, 0xb6, 0x4e, 0x72, 0x49, 0x9f, 0xf5, 0x92, 0xcf, 0x5f, 0xc3,
	0x8e, 0x11, 0xdf, 0x46, 0x61, 0xec, 0xf9, 0x27, 0x41, 0x48, 0x25, 0x09, 0xbf, 0x84, 0xcd, 0xb3,
	0x20, 0xa4, 0x2e, 0xcb, 0x8f, 0x32, 0x13, 0x7d, 0x86, 0xb2, 0xd4, 0xe1, 0x29, 0x3e, 0x87, 0xed,
	0xea, 0xe2, 0x75, 0xa2, 0xf9, 0x08, 0x40, 0xa4, 0x7a, 0x1a, 0xbc, 0x13, 0x1f, 0xb5, 0x45, 0x14,
	0x8e, 0xd8, 0xc1, 0x3b, 0x7e, 0x5e, 0x66, 0x17, 0x37, 0xd1, 0x25, 0x67, 0xad, 0x4f, 0x84, 0xa0,
	0xfd, 0x11, 0x06, 0xf8, 0xed, 0x3c, 0x4e, 0x32, 0x19, 0xe8, 0xe7, 0xd0, 0xf1, 0xdf, 0x88, 0x73,
	0x51, 0xe3, 0x1f, 0xa5, 0x70, 0x67, 0x1c, 0xf1, 0xb3, 0xd0, 0xf6, 0xdf, 0xf0, 0x53, 0xf0, 0x00,
	0x5a, 0x61, 0x70, 0x15, 0x64, 0xb9, 0x27, 0x21, 0xa0, 0x5f, 0xc1, 0x76, 0x4a, 0x43, 0x3a, 0xcb,
	0xdc, 0xfc, 0xc8, 0x04, 0xf9, 0x31, 0x51, 0x88, 0x2a, 0x26, 0x26, 0x05, 0xae, 0xfd, 0xa9, 0x06,
	0x3d, 0xe9, 0x7d, 0x9d, 0x9d, 0x56, 0x93, 0xa5, 0xfe, 0x1e, 0xc9, 0x52, 0xcd, 0xd9, 0xc6, 0x7f,
	0xce, 0x59, 0x0d, 0x81, 0x7a, 0x4a, 0xb3, 0x11, 0xf5, 0x7c, 0x9a, 0xe4, 0xdc, 0x68, 0x5f, 0xc3,
	0x66, 0x09, 0x5b, 0x23, 0x62, 0xed, 0x2f, 0x35, 0x40, 0x66, 0x94, 0xd2, 0x24, 0x63, 0xe1, 0xa5,
	0x92, 0xec, 0xf5, 0xb3, 0xfe, 0x21, 0xb4, 0xd3, 0x20, 0xa4, 0x91, 0xa0, 0xbd, 0x4b, 0x72, 0x09,
	0x7d, 0x0c, 0xbd, 0x28, 0x76, 0x83, 0x28, 0xa2, 0x89, 0x1b, 0xf8, 0x7c, 0x87, 0x5d, 0xb6, 0xce,
	0x64, 0x88, 0xe9, 0xaf, 0xdc, 0x2d, 0xcd, 0x95, 0xbb, 0x05, 0x7d, 0x08, 0x9d, 0xd9, 0x05, 0x9d,
	0x5d, 0xba, 0xf1, 0xb0, 0x25, 0xec, 0x72, 0xd1, 0xd2, 0xfe, 0x56, 0x03, 0xb5, 0x12, 0xf8, 0x3a,
	0xdf, 0xe9, 0x11, 0x28, 0xcb, 0xdb, 0x44, 0x1c, 0x93, 0x6e, 0xf6, 0xef, 0x6e, 0x9c, 0xc6, 0xbd,
	0x37, 0x8e, 0x0a, 0x8d, 0xc0, 0x4f, 0x87, 0xcd, 0xbd, 0xc6, 0x7e, 0x83, 0xb0, 0x21, 0xfa, 0x14,
	0x36, 0x83, 0xf3, 0x28, 0x4e, 0xa8, 0x1b, 0x44, 0x3e, 0x7d, 0x4b, 0xc5, 0x65, 0xd4, 0x22, 0x03,
	0x81, 0x9a, 0x02, 0xd4, 0xfe, 0x5c, 0xb0, 0xce, 0x3e, 0x71, 0x99, 0xf5, 0x35, 0x0b, 0xf8, 0xff,
	0x87, 0xf5, 0x12, 0xb9, 0x79, 0x7c, 0x3f, 0x25, 0x72, 0x7f, 0xa8, 0x41, 0xdb, 0x2e, 0xf2, 0x91,
	0x26, 0x49, 0x9c, 0xb8, 0xb3, 0xd8, 0x97, 0x65, 0x63, 0x49, 0x28, 0x9b, 0x39, 0x8e, 0x7d, 0x46,
	0xa8, 0x1c, 0x32, 0xaf, 0x57, 0xe9, 0x79, 0x5e, 0x38, 0xd9, 0x10, 0x3d, 0x87, 0xfe, 0x2c, 0xbc,
	0x49, 0x33, 0xc6, 0x64, 0x74, 0x16, 0xe7, 0x39, 0xba, 0x23, 0xad, 0x1c, 0x8b, 0x39, 0x33, 0x3a,
	0x8b, 0x49, 0x6f, 0xb6, 0x14, 0xb4, 0xef, 0xa0, 0x4f, 0xbc, 0xb3, 0xec, 0x24, 0x0e, 0xc3, 0xf8,
	0x96, 0x26, 0xac, 0xbd, 0xf2, 0x7c, 0x3f, 0xa1, 0xa9, 0xbc, 0xf5, 0xa4, 0xc8, 0xaa, 0x75, 0x12,
	0x87, 0xb2, 0x32, 0xf2, 0x31, 0x7a, 0x5c, 0x90, 0xdd, 0xe0, 0x51, 0x3f, 0x28, 0xc8, 0xa6, 0xc9,
	0xf7, 0x34, 0x59, 0xc9, 0xe2, 0x1f, 0x6a, 0xd0, 0x2b, 0x05, 0x82, 0x76, 0xa1, 0x9b, 0x50, 0x3f,
	0x48, 0xe8, 0x2c, 0x93, 0x17, 0x9b, 0x94, 0x19, 0x8b, 0x21, 0x2f, 0x14, 0xae, 0x0c, 0x47, 0x6c,
	0x76, 0x20, 0x50, 0x3d, 0x0f, 0xea, 0x10, 0x94, 0xb3, 0x3c, 0x74, 0x51, 0x27, 0x7b, 0xcb, 0x18,
	0xca, 0xfb, 0x22, 0x4b, 0x35, 0xed, 0x3b, 0x68, 0xb2, 0x1b, 0xe3, 0xbf, 0xa8, 0x1e, 0xd5, 0x93,
	0x5f, 0x7f, 0x8f, 0x32, 0x78, 0x0d, 0x2d, 0xb1, 0x94, 0xdd, 0x2e, 0x6c, 0x50, 0xbe, 0xbc, 0x14,
	0x8e, 0xf0, 0x02, 0x32, 0x84, 0xce, 0x05, 0xdf, 0x18, 0xdb, 0x27, 0xab, 0xf6, 0x52, 0x44, 0x4f,
	0xe5, 0xc2, 0x24, 0xbe, 0x95, 0x5b, 0x54, 0xab, 0x4d, 0x59, 0x7c, 0x9b, 0x9b, 0x22, 0xf1, 0x6d,
	0xaa, 0x69, 0xd0, 0x95, 0x70, 0xa9, 0xd5, 0xa8, 0x55, 0x5a, 0x8d, 0x99, 0xe8, 0x9d, 0x44, 0x68,
	0xfb, 0x55, 0xdf, 0xa5, 0x94, 0xf9, 0x56, 0x94, 0xea, 0x22, 0x96, 0xc7, 0xc0, 0xc9, 0x28, 0x87,
	0xb2, 0x55, 0x26, 0x8c, 0x45, 0xd2, 0x8d, 0xc4, 0x80, 0x3b, 0x29, 0x38, 0x59, 0xcf, 0x09, 0x27,
	0xf9, 0x3e, 0x27, 0xcc, 0x1e, 0x77, 0x42, 0xc5, 0x20, 0xd5, 0xbe, 0x84, 0x4e, 0xee, 0x19, 0x6d,
	0x42, 0x3d, 0xf0, 0x39, 0xb5, 0x0d, 0x52, 0x0f, 0xfc, 0xd2, 0xe6, 0xeb, 0x95, 0xcd, 0xbb, 0xd0,
	0xc9, 0xed, 0xdc, 0x59, 0xf2, 0x21, 0x74, 0xce, 0x92, 0xf8, 0x8a, 0x15, 0xa3, 0x3a, 0x07, 0xdb,
	0x4c, 0x34, 0x7d, 0xb4, 0x03, 0xad, 0x2c, 0x96, 0x35, 0xaa, 0x41, 0x9a, 0x59, 0x6c, 0x96, 0x1d,
	0x34, 0x2b, 0x0e, 0x22, 0x68, 0x8b, 0x4d, 0xa1, 0x4f, 0x4a, 0xbd, 0x62, 0xb9, 0x6b, 0x91, 0x20,
	0xff, 0xf6, 0xff, 0x6b, 0x43, 0xa9, 0x3d, 0x85, 0x16, 0x6f, 0xb4, 0x59, 0x59, 0xb8, 0xa4, 0x0b,
	0xf9, 0x5a, 0xba, 0xa4, 0x0b, 0xd6, 0x65, 0xf0, 0xa0, 0x64, 0x97, 0xcb, 0x85, 0x83, 0xbf, 0xb2,
	0x4e, 0xf3, 0x8e, 0x55, 0x84, 0x60, 0x73, 0x42, 0xac, 0x09, 0x26, 0xce, 0x6b, 0xd7, 0x1c, 0x3b,
	0xcf, 0x0e, 0xd5, 0x0d, 0xb4, 0x03, 0x5b, 0x05, 0x66, 0x3b, 0xc4, 0x1c, 0x9f, 0xaa, 0xb5, 0x8a,
	0xe2, 0xc9, 0xc8, 0xd2, 0x1d, 0xb5, 0x5e, 0x51, 0x34, 0xac, 0xe9, 0xd1, 0x08, 0xab, 0x8d, 0x0a,
	0x38, 0x15, 0x26, 0x9b, 0xab, 0x6e, 0x9e, 0x7f, 0xa5, 0xb6, 0xee, 0x28, 0x3e, 0xff, 0x4a, 0x6d,
	0xa3, 0x6d, 0x18, 0x14, 0xe0, 0xd1, 0xc8, 0x3a, 0x52, 0x3b, 0x07, 0x3f, 0xd6, 0x41, 0x29, 0x2a,
	0x22, 0xeb, 0x44, 0xed, 0xe9, 0xf1, 0x31, 0xb6, 0x6d, 0x75, 0x03, 0x01, 0xb4, 0x4f, 0x74, 0x73,
	0x84, 0x0d, 0xb5, 0x86, 0xb6, 0xa0, 0x37, 0xd1, 0x89, 0xfe, 0xc2, 0xc5, 0x84, 0x58, 0x44, 0xad,
	0x33, 0x53, 0x47, 0xba, 0x8d, 0x5d, 0xe3, 0x28, 0x87, 0x1a, 0x48, 0x85, 0x3e, 0x1e, 0x9f, 0x9a,
	0x63, 0x9c, 0x23, 0x4d, 0x86, 0xd8, 0xaf, 0x6d, 0x07, 0xcb, 0x65, 0x2d, 0xb6, 0x8c, 0xe8, 0x27,
	0x8e, 0x4b, 0xb0, 0x61, 0x12, 0x7c, 0xec, 0xa8, 0x6d, 0xf4, 0x73, 0x78, 0xc4, 0xa1, 0x11, 0xd6,
	0x0d, 0x4c, 0xdc, 0xb1, 0xe5, 0xb8, 0xaf, 0xb1, 0xe3, 0xe2, 0x11, 0x3e, 0x76, 0xb0, 0xa1, 0x76,
	0xd8, 0xf6, 0x84, 0x82, 0x75, 0x9a, 0xdb, 0xe9, 0xa2, 0x01, 0x28, 0xd3, 0xdf, 0x8d, 0x72, 0x51,
	0x61, 0x66, 0xd9, 0x3a, 0xae, 0xf6, 0xc2, 0x32, 0xb0, 0x0a, 0x85, 0xd9, 0xb1, 0xe5, 0xea, 0x2f,
	0x75, 0x73, 0xa4, 0x1f, 0x8d, 0xb0, 0x7b, 0x62, 0x8d, 0x46, 0xd6, 0x2b, 0x4c, 0x6c, 0xb5, 0x87,
	0x34, 0xf8, 0xf8, 0xae, 0x82, 0x3e, 0x3a, 0xb5, 0x5c, 0x1b, 0x93, 0x97, 0x4c, 0xa7, 0x8f, 0x3e,
	0x80, 0xed, 0x09, 0x26, 0x2f, 0x4c, 0xdb, 0x36, 0xad, 0xb1, 0x6b, 0xe0, 0xb1, 0x89, 0x0d, 0x75,
	0x70, 0xf0, 0x07, 0xe8, 0x17, 0x75, 0x90, 0x55, 0xed, 0x4d, 0x00, 0x62, 0x8d, 0xb0, 0x3b, 0x1d,
	0xdb, 0xbc, 0xa1, 0x67, 0xbb, 0x64, 0x32, 0xc1, 0xba, 0xc1, 0xcc, 0xaa, 0x35, 0x34, 0x84, 0x07,
	0x1c, 0xe2, 0x0e, 0xf0, 0xef, 0xf1, 0xf1, 0xd4, 0xe1, 0x33, 0x75, 0x46, 0x12, 0x9f, 0x19, 0x61,
	0x9d, 0x8c, 0x31, 0x51, 0x9b, 0x07, 0x9f, 0x40, 0xbf, 0x5c, 0xee, 0x51, 0x17, 0x9a, 0x06, 0xd6,
	0x0d, 0x75, 0x03, 0x29, 0xd0, 0xd2, 0x47, 0xe6, 0x4b, 0xac, 0xd6, 0x0e, 0xf6, 0xa0, 0x2d, 0x1a,
	0x60, 0xf6, 0x9d, 0x8c, 0xa3, 0x31, 0xdb, 0xf5, 0x86, 0x18, 0x63, 0xe3, 0x94, 0x69, 0xdc, 0x42,
	0xcf, 0xd1, 0xed, 0xdf, 0xba, 0xb6, 0xa3, 0x3b, 0x53, 0x9b, 0xf9, 0xe1, 0xe2, 0x04, 0x8f, 0x0d,
	0x76, 0xea, 0x36, 0x18, 0xb1, 0x1c, 0x39, 0xb6, 0x5e, 0x4c, 0xa6, 0x8e, 0x38, 0x89, 0x52, 0xeb,
	0x15, 0x31, 0x39, 0x52, 0x67, 0x54, 0x73, 0xc4, 0xb0, 0xc6, 0xec, 0x04, 0x6e, 0xe5, 0x56, 0xf3,
	0xa3, 0xd1, 0x2c, 0x56, 0xd8, 0x8e, 0x35, 0x99, 0x60, 0x43, 0x6d, 0x1d, 0xfe, 0xbd, 0x09, 0x90,
	0xff, 0xc3, 0x98, 0xcf, 0x52, 0x74, 0x04, 0x5d, 0xdb, 0x5b, 0xf0, 0x3f, 0x1b, 0x68, 0x77, 0x59,
	0xa4, 0x56, 0x7f, 0x89, 0xec, 0x0e, 0xef, 0x9d, 0x9b, 0x87, 0x0b, 0x6d, 0x03, 0x3d, 0x85, 0xc6,
	0xf4, 0x3a, 0x44, 0xa8, 0x48, 0xe1, 0xe2, 0x8f, 0xc6, 0xae, 0x5a, 0xc1, 0xb8, 0xfa, 0x17, 0x35,
	0x84, 0xa1, 0x57, 0x7a, 0x46, 0x2d, 0xfd, 0xde, 0x7d, 0xc9, 0x2d, 0xfd, 0xae, 0xbe, 0xbb, 0xb4,
	0x0d, 0xf4, 0x1b, 0xe8, 0x97, 0x1f, 0x40, 0xe8, 0x51, 0xf1, 0xf8, 0xb8, 0xfb, 0xa6, 0xda, 0xfd,
	0xd9, 0xfd, 0x93, 0x32, 0xa4, 0xaf, 0xa1, 0x2d, 0x1e, 0x17, 0xe8, 0x83, 0xa2, 0xfc, 0x96, 0x9f,
	0x3a, 0xbb, 0x3b, 0xab, 0xb0, 0x5c, 0xf9, 0x0d, 0x28, 0x45, 0x9f, 0x8f, 0x8a, 0x70, 0x57, 0x9f,
	0x03, 0xbb, 0x0f, 0xef, 0x99, 0x11, 0xdb, 0xc0, 0xd0, 0x2b, 0x35, 0xcd, 0x4b, 0x36, 0xee, 0x3e,
	0x01, 0x96, 0x6c, 0xac, 0x76, 0xd9, 0x65, 0x33, 0xbc, 0x3d, 0x5c, 0x35, 0x53, 0xee, 0x69, 0x57,
	0xcd, 0x2c, 0xfb, 0x49, 0x6d, 0x03, 0x7d, 0x09, 0xad, 0xe9, 0x75, 0x88, 0xdf, 0xbe, 0xff, 0xe7,
	0x7c, 0xd3, 0xe6, 0xff, 0xd4, 0x9e, 0xfd, 0x33, 0x00, 0x00, 0xff, 0xff, 0xcc, 0x6a, 0xa5, 0x3c,
	0x63, 0x13, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UltipaRpcsClient is the client API for UltipaRpcs service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UltipaRpcsClient interface {
	// 1.Sends a greeting
	SayHello(ctx context.Context, in *HelloUltipaRequest, opts ...grpc.CallOption) (*HelloUltipaReply, error)
	//2.uql
	Uql(ctx context.Context, in *UqlRequest, opts ...grpc.CallOption) (UltipaRpcs_UqlClient, error)
	//3.用户设置(用于存储用户配置信息,用户自主控制)
	UserSetting(ctx context.Context, in *UserSettingRequest, opts ...grpc.CallOption) (*UserSettingReply, error)
	//4.下载算法生成文件
	DownloadFile(ctx context.Context, in *DownloadFileRequest, opts ...grpc.CallOption) (UltipaRpcs_DownloadFileClient, error)
	//5.导出点,边数据
	Export(ctx context.Context, in *ExportRequest, opts ...grpc.CallOption) (UltipaRpcs_ExportClient, error)
	//6. 获取raft的leader
	GetLeader(ctx context.Context, in *GetLeaderRequest, opts ...grpc.CallOption) (*GetLeaderReply, error)
	//7.插入点
	InsertNodes(ctx context.Context, in *InsertNodesRequest, opts ...grpc.CallOption) (*InsertNodesReply, error)
	//8.插入边
	InsertEdges(ctx context.Context, in *InsertEdgesRequest, opts ...grpc.CallOption) (*InsertEdgesReply, error)
	//9.uql扩展，以下命令在此接口执行执行 top, kill showTask, stopTask,clearTask show() stat listGraph
	// listAlgo getGraph createPolicy, deletePolicy, listPolicy, getPolicy,
	// grant, revoke, listPrivilege, getUser, getSelfInfo, createUser, updateUser, deleteUser, showIndex
	UqlEx(ctx context.Context, in *UqlRequest, opts ...grpc.CallOption) (UltipaRpcs_UqlExClient, error)
}

type ultipaRpcsClient struct {
	cc *grpc.ClientConn
}

func NewUltipaRpcsClient(cc *grpc.ClientConn) UltipaRpcsClient {
	return &ultipaRpcsClient{cc}
}

func (c *ultipaRpcsClient) SayHello(ctx context.Context, in *HelloUltipaRequest, opts ...grpc.CallOption) (*HelloUltipaReply, error) {
	out := new(HelloUltipaReply)
	err := c.cc.Invoke(ctx, "/ultipa.UltipaRpcs/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ultipaRpcsClient) Uql(ctx context.Context, in *UqlRequest, opts ...grpc.CallOption) (UltipaRpcs_UqlClient, error) {
	stream, err := c.cc.NewStream(ctx, &_UltipaRpcs_serviceDesc.Streams[0], "/ultipa.UltipaRpcs/Uql", opts...)
	if err != nil {
		return nil, err
	}
	x := &ultipaRpcsUqlClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type UltipaRpcs_UqlClient interface {
	Recv() (*UqlReply, error)
	grpc.ClientStream
}

type ultipaRpcsUqlClient struct {
	grpc.ClientStream
}

func (x *ultipaRpcsUqlClient) Recv() (*UqlReply, error) {
	m := new(UqlReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *ultipaRpcsClient) UserSetting(ctx context.Context, in *UserSettingRequest, opts ...grpc.CallOption) (*UserSettingReply, error) {
	out := new(UserSettingReply)
	err := c.cc.Invoke(ctx, "/ultipa.UltipaRpcs/UserSetting", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ultipaRpcsClient) DownloadFile(ctx context.Context, in *DownloadFileRequest, opts ...grpc.CallOption) (UltipaRpcs_DownloadFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &_UltipaRpcs_serviceDesc.Streams[1], "/ultipa.UltipaRpcs/DownloadFile", opts...)
	if err != nil {
		return nil, err
	}
	x := &ultipaRpcsDownloadFileClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type UltipaRpcs_DownloadFileClient interface {
	Recv() (*DownloadFileReply, error)
	grpc.ClientStream
}

type ultipaRpcsDownloadFileClient struct {
	grpc.ClientStream
}

func (x *ultipaRpcsDownloadFileClient) Recv() (*DownloadFileReply, error) {
	m := new(DownloadFileReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *ultipaRpcsClient) Export(ctx context.Context, in *ExportRequest, opts ...grpc.CallOption) (UltipaRpcs_ExportClient, error) {
	stream, err := c.cc.NewStream(ctx, &_UltipaRpcs_serviceDesc.Streams[2], "/ultipa.UltipaRpcs/Export", opts...)
	if err != nil {
		return nil, err
	}
	x := &ultipaRpcsExportClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type UltipaRpcs_ExportClient interface {
	Recv() (*ExportReply, error)
	grpc.ClientStream
}

type ultipaRpcsExportClient struct {
	grpc.ClientStream
}

func (x *ultipaRpcsExportClient) Recv() (*ExportReply, error) {
	m := new(ExportReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *ultipaRpcsClient) GetLeader(ctx context.Context, in *GetLeaderRequest, opts ...grpc.CallOption) (*GetLeaderReply, error) {
	out := new(GetLeaderReply)
	err := c.cc.Invoke(ctx, "/ultipa.UltipaRpcs/GetLeader", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ultipaRpcsClient) InsertNodes(ctx context.Context, in *InsertNodesRequest, opts ...grpc.CallOption) (*InsertNodesReply, error) {
	out := new(InsertNodesReply)
	err := c.cc.Invoke(ctx, "/ultipa.UltipaRpcs/InsertNodes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ultipaRpcsClient) InsertEdges(ctx context.Context, in *InsertEdgesRequest, opts ...grpc.CallOption) (*InsertEdgesReply, error) {
	out := new(InsertEdgesReply)
	err := c.cc.Invoke(ctx, "/ultipa.UltipaRpcs/InsertEdges", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ultipaRpcsClient) UqlEx(ctx context.Context, in *UqlRequest, opts ...grpc.CallOption) (UltipaRpcs_UqlExClient, error) {
	stream, err := c.cc.NewStream(ctx, &_UltipaRpcs_serviceDesc.Streams[3], "/ultipa.UltipaRpcs/UqlEx", opts...)
	if err != nil {
		return nil, err
	}
	x := &ultipaRpcsUqlExClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type UltipaRpcs_UqlExClient interface {
	Recv() (*UqlReply, error)
	grpc.ClientStream
}

type ultipaRpcsUqlExClient struct {
	grpc.ClientStream
}

func (x *ultipaRpcsUqlExClient) Recv() (*UqlReply, error) {
	m := new(UqlReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// UltipaRpcsServer is the server API for UltipaRpcs service.
type UltipaRpcsServer interface {
	// 1.Sends a greeting
	SayHello(context.Context, *HelloUltipaRequest) (*HelloUltipaReply, error)
	//2.uql
	Uql(*UqlRequest, UltipaRpcs_UqlServer) error
	//3.用户设置(用于存储用户配置信息,用户自主控制)
	UserSetting(context.Context, *UserSettingRequest) (*UserSettingReply, error)
	//4.下载算法生成文件
	DownloadFile(*DownloadFileRequest, UltipaRpcs_DownloadFileServer) error
	//5.导出点,边数据
	Export(*ExportRequest, UltipaRpcs_ExportServer) error
	//6. 获取raft的leader
	GetLeader(context.Context, *GetLeaderRequest) (*GetLeaderReply, error)
	//7.插入点
	InsertNodes(context.Context, *InsertNodesRequest) (*InsertNodesReply, error)
	//8.插入边
	InsertEdges(context.Context, *InsertEdgesRequest) (*InsertEdgesReply, error)
	//9.uql扩展，以下命令在此接口执行执行 top, kill showTask, stopTask,clearTask show() stat listGraph
	// listAlgo getGraph createPolicy, deletePolicy, listPolicy, getPolicy,
	// grant, revoke, listPrivilege, getUser, getSelfInfo, createUser, updateUser, deleteUser, showIndex
	UqlEx(*UqlRequest, UltipaRpcs_UqlExServer) error
}

// UnimplementedUltipaRpcsServer can be embedded to have forward compatible implementations.
type UnimplementedUltipaRpcsServer struct {
}

func (*UnimplementedUltipaRpcsServer) SayHello(ctx context.Context, req *HelloUltipaRequest) (*HelloUltipaReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (*UnimplementedUltipaRpcsServer) Uql(req *UqlRequest, srv UltipaRpcs_UqlServer) error {
	return status.Errorf(codes.Unimplemented, "method Uql not implemented")
}
func (*UnimplementedUltipaRpcsServer) UserSetting(ctx context.Context, req *UserSettingRequest) (*UserSettingReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserSetting not implemented")
}
func (*UnimplementedUltipaRpcsServer) DownloadFile(req *DownloadFileRequest, srv UltipaRpcs_DownloadFileServer) error {
	return status.Errorf(codes.Unimplemented, "method DownloadFile not implemented")
}
func (*UnimplementedUltipaRpcsServer) Export(req *ExportRequest, srv UltipaRpcs_ExportServer) error {
	return status.Errorf(codes.Unimplemented, "method Export not implemented")
}
func (*UnimplementedUltipaRpcsServer) GetLeader(ctx context.Context, req *GetLeaderRequest) (*GetLeaderReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLeader not implemented")
}
func (*UnimplementedUltipaRpcsServer) InsertNodes(ctx context.Context, req *InsertNodesRequest) (*InsertNodesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InsertNodes not implemented")
}
func (*UnimplementedUltipaRpcsServer) InsertEdges(ctx context.Context, req *InsertEdgesRequest) (*InsertEdgesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InsertEdges not implemented")
}
func (*UnimplementedUltipaRpcsServer) UqlEx(req *UqlRequest, srv UltipaRpcs_UqlExServer) error {
	return status.Errorf(codes.Unimplemented, "method UqlEx not implemented")
}

func RegisterUltipaRpcsServer(s *grpc.Server, srv UltipaRpcsServer) {
	s.RegisterService(&_UltipaRpcs_serviceDesc, srv)
}

func _UltipaRpcs_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloUltipaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UltipaRpcsServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ultipa.UltipaRpcs/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UltipaRpcsServer).SayHello(ctx, req.(*HelloUltipaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UltipaRpcs_Uql_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(UqlRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UltipaRpcsServer).Uql(m, &ultipaRpcsUqlServer{stream})
}

type UltipaRpcs_UqlServer interface {
	Send(*UqlReply) error
	grpc.ServerStream
}

type ultipaRpcsUqlServer struct {
	grpc.ServerStream
}

func (x *ultipaRpcsUqlServer) Send(m *UqlReply) error {
	return x.ServerStream.SendMsg(m)
}

func _UltipaRpcs_UserSetting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserSettingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UltipaRpcsServer).UserSetting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ultipa.UltipaRpcs/UserSetting",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UltipaRpcsServer).UserSetting(ctx, req.(*UserSettingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UltipaRpcs_DownloadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownloadFileRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UltipaRpcsServer).DownloadFile(m, &ultipaRpcsDownloadFileServer{stream})
}

type UltipaRpcs_DownloadFileServer interface {
	Send(*DownloadFileReply) error
	grpc.ServerStream
}

type ultipaRpcsDownloadFileServer struct {
	grpc.ServerStream
}

func (x *ultipaRpcsDownloadFileServer) Send(m *DownloadFileReply) error {
	return x.ServerStream.SendMsg(m)
}

func _UltipaRpcs_Export_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExportRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UltipaRpcsServer).Export(m, &ultipaRpcsExportServer{stream})
}

type UltipaRpcs_ExportServer interface {
	Send(*ExportReply) error
	grpc.ServerStream
}

type ultipaRpcsExportServer struct {
	grpc.ServerStream
}

func (x *ultipaRpcsExportServer) Send(m *ExportReply) error {
	return x.ServerStream.SendMsg(m)
}

func _UltipaRpcs_GetLeader_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLeaderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UltipaRpcsServer).GetLeader(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ultipa.UltipaRpcs/GetLeader",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UltipaRpcsServer).GetLeader(ctx, req.(*GetLeaderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UltipaRpcs_InsertNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UltipaRpcsServer).InsertNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ultipa.UltipaRpcs/InsertNodes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UltipaRpcsServer).InsertNodes(ctx, req.(*InsertNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UltipaRpcs_InsertEdges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertEdgesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UltipaRpcsServer).InsertEdges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ultipa.UltipaRpcs/InsertEdges",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UltipaRpcsServer).InsertEdges(ctx, req.(*InsertEdgesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UltipaRpcs_UqlEx_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(UqlRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UltipaRpcsServer).UqlEx(m, &ultipaRpcsUqlExServer{stream})
}

type UltipaRpcs_UqlExServer interface {
	Send(*UqlReply) error
	grpc.ServerStream
}

type ultipaRpcsUqlExServer struct {
	grpc.ServerStream
}

func (x *ultipaRpcsUqlExServer) Send(m *UqlReply) error {
	return x.ServerStream.SendMsg(m)
}

var _UltipaRpcs_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ultipa.UltipaRpcs",
	HandlerType: (*UltipaRpcsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _UltipaRpcs_SayHello_Handler,
		},
		{
			MethodName: "UserSetting",
			Handler:    _UltipaRpcs_UserSetting_Handler,
		},
		{
			MethodName: "GetLeader",
			Handler:    _UltipaRpcs_GetLeader_Handler,
		},
		{
			MethodName: "InsertNodes",
			Handler:    _UltipaRpcs_InsertNodes_Handler,
		},
		{
			MethodName: "InsertEdges",
			Handler:    _UltipaRpcs_InsertEdges_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Uql",
			Handler:       _UltipaRpcs_Uql_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "DownloadFile",
			Handler:       _UltipaRpcs_DownloadFile_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Export",
			Handler:       _UltipaRpcs_Export_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "UqlEx",
			Handler:       _UltipaRpcs_UqlEx_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "ultipa.proto",
}
